force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <label>License</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Examples_of_KYC_Status__c.field-meta.xml
<CustomField>
    <fullName>Examples_of_KYC_Status__c</fullName>
    <label>Examples of KYC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Not Availiable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/Policies_Procedures_Status__c.field-meta.xml
<CustomField>
    <fullName>Policies_Procedures_Status__c</fullName>
    <label>Policies &amp; Procedures Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Not Availiable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Type__c/License_Type__c.object-meta.xml
<CustomObject>
    <label>License Type</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>License Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Type__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>License Types</relationshipLabel>
    <relationshipName>License_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/License_Type__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Policies &amp; Procedures</fullName>
            </value>
            <value>
                <fullName>Examples of KYC packs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Type__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AML/KYC policy</fullName>
            </value>
            <value>
                <fullName>CDD procedure</fullName>
            </value>
            <value>
                <fullName>Sanction/PEP screening policy</fullName>
            </value>
            <value>
                <fullName>Transaction Monitoring policy</fullName>
            </value>
            <value>
                <fullName>Risk Appetite Statement</fullName>
            </value>
            <value>
                <fullName>EWRA</fullName>
            </value>
            <value>
                <fullName>Compliance Audit Report</fullName>
            </value>
            <value>
                <fullName>CV of Compliance Officer</fullName>
            </value>
            <value>
                <fullName>Organizational Structure</fullName>
            </value>
            <value>
                <fullName>Agreement with KYC vendor</fullName>
            </value>
            <value>
                <fullName>Agreement with Sanction Screening vendor</fullName>
            </value>
            <value>
                <fullName>Agreement with Crypto Transaction Monitoring vendor</fullName>
            </value>
            <value>
                <fullName>Full List of available Cryptocurrencies</fullName>
            </value>
            <value>
                <fullName>Agreement with Liquidity provider (if Applicable)</fullName>
            </value>
            <value>
                <fullName>Business Plan (for start ups)</fullName>
            </value>
            <value>
                <fullName>Disclaimer within the website about age limits, human trafficking, escorting and prostitution prevention</fullName>
            </value>
            <value>
                <fullName>Agreement with the main partners</fullName>
            </value>
            <value>
                <fullName>Proof of Insurance</fullName>
            </value>
            <value>
                <fullName>Content Monitoring policy/procedure</fullName>
            </value>
            <value>
                <fullName>Policy about age limits, human trafficking, child pornography, escorting and prostitution prevention</fullName>
            </value>
            <value>
                <fullName>1 Example</fullName>
            </value>
            <value>
                <fullName>2 Example</fullName>
            </value>
            <value>
                <fullName>3 Example</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LicenseTypeTriggerHandler.cls
public class LicenseTypeTriggerHandler {
    
    public void onAfterUpdate(List<License_Type__c> listOfLicenseType) {

        List<License_Type__c> listOfPoliciesAndProcedures = new List<License_Type__c>();
        List<License_Type__c> listOfExamplesOfKycPacks = new List<License_Type__c>();

        for(License_Type__c licenseType : listOfLicenseType) {
            if(licenseType.Section__c == 'Policies & Procedures') {
                listOfPoliciesAndProcedures.add(licenseType);
            } else if(licenseType.Section__c == 'Examples of KYC packs') {
                listOfExamplesOfKycPacks.add(licenseType);
            }
        }

        if(!listOfPoliciesAndProcedures.isEmpty()) {
            updateLicenseStatus(listOfPoliciesAndProcedures, 'Policies & Procedures');
        }

        if(!listOfExamplesOfKycPacks.isEmpty()) {
            updateLicenseStatus(listOfExamplesOfKycPacks, 'Examples of KYC packs');
        }
    }

    public static void updateLicenseStatus(List<License_Type__c> listOfLicenseType, String nameOfSection) {

        String finalStatusOfLicense;
        Set<Id> setOfIdLicense = new Set<Id>();
        List<License__c> listOfLicensesForUpdate = new List<License__c>();
        Map<Id, Set<String>> mapOfStatusesByLicense = new Map<Id, Set<String>>();
        Map<Id, String> mapOfFinalStatusById = new Map<Id, String>();

        for(License_Type__c license : listOfLicenseType) {
            setOfIdLicense.add(license.License__c);
        }

        List<License_Type__c> listOfLicenseTypes = [SELECT Id, Status__c, Section__c, Type__c, License__c
                                                    FROM License_Type__c 
                                                    WHERE License__c IN : setOfIdLicense 
                                                    AND Section__c = :nameOfSection];

        for (License_Type__c license : listOfLicenseTypes) {

            Id idOfLicenseType = license.License__c;
    
            String statusOfLicenseType = license.Status__c;
    
            if (mapOfStatusesByLicense.containsKey(idOfLicenseType)) {
                mapOfStatusesByLicense.get(idOfLicenseType).add(statusOfLicenseType);
            } else {
                Set<String> setOfLicenseTypeStatuses = new Set<String>{statusOfLicenseType};
                mapOfStatusesByLicense.put(idOfLicenseType, setOfLicenseTypeStatuses);
            }
        }

        for (Id licenseId : mapOfStatusesByLicense.keySet()) {

            Set<String> setOfStatuses = mapOfStatusesByLicense.get(licenseId);
            if(setOfStatuses.contains('Rejected')) {
                mapOfFinalStatusById.put(licenseId, 'Rejected');
            } else if(setOfStatuses.contains('Postponed')) {
                mapOfFinalStatusById.put(licenseId, 'Postponed');
            } else if(setOfStatuses.size() == 1 && setOfStatuses.contains('Approved')) {
                mapOfFinalStatusById.put(licenseId, 'Approved');
            } else if(setOfStatuses.size() == 2 && setOfStatuses.contains('Approved') && setOfStatuses.contains('Not Applicable')) {
                mapOfFinalStatusById.put(licenseId, 'Approved');
            } else {
                mapOfFinalStatusById.put(licenseId, 'Pending');
            }
        }

        for(Id licenseId : mapOfFinalStatusById.keySet()) {
            if(nameOfSection == 'Policies & Procedures') {
                listOfLicensesForUpdate.add(new License__c(Id = licenseId, Policies_Procedures_Status__c = mapOfFinalStatusById.get(licenseId)));
            } else if(nameOfSection == 'Examples of KYC packs') {
                listOfLicensesForUpdate.add(new License__c(Id = licenseId, Examples_of_KYC_Status__c = mapOfFinalStatusById.get(licenseId)));
            }
        }
        update listOfLicensesForUpdate;
    }
}