force-app/main/core/objects/Noda_Custom_Settings__c/Noda_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Noda Custom Settings</label>
</CustomObject>

force-app/main/core/objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Noda Go</fullName>
            </value>
            <value>
                <fullName>Noda Buffet</fullName>
            </value>
            <value>
                <fullName>Pay In</fullName>
            </value>
            <value>
                <fullName>Pay Out</fullName>
            </value>
            <value>
                <fullName>Payment links</fullName>
            </value>
            <value>
                <fullName>Trusted Payments</fullName>
            </value>
            <value>
                <fullName>Cards</fullName>
            </value>
            <value>
                <fullName>KYW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/classes/triggerHandlers/OpportunityTriggerHandler.cls
public with sharing class OpportunityTriggerHandler extends TriggerHandler {
    
    public override void afterInsert() {
        Map<Id, Map<String,String>> accountIdByChangedStage = new Map<Id, Map<String,String>>();

        for (Opportunity opportunity : (List<Opportunity>) Trigger.new) {
            if (opportunity.Service_Type__c != null && opportunity.StageName != null) {
                if (!accountIdByChangedStage.containsKey(opportunity.AccountId)) {
                    accountIdByChangedStage.put(opportunity.AccountId, new Map<String, String>());
                }
                accountIdByChangedStage.get(opportunity.AccountId).put(opportunity.Service_Type__c, opportunity.StageName);
            }
        }

        if (!accountIdByChangedStage.isEmpty()) {
            OpportunityService.updateProductStatusOnAccount(accountIdByChangedStage);
        }
    }

    public override void afterUpdate() {
        Map<Id, Opportunity> oldMap = (Map<Id, Opportunity>) Trigger.oldMap;
        Map<Id, Opportunity> newMap = (Map<Id, Opportunity>) Trigger.newMap;
        Map<Id, Map<String,String>> accountIdByChangedStage = new Map<Id, Map<String,String>>();
        Noda_Custom_Settings__c settingsOfNoda = SettingUtils.settingsOfNoda;

        for (Opportunity opportunity : newMap.values()) {
            if (opportunity.StageName != oldMap.get(opportunity.Id).StageName && opportunity.Service_Type__c != null) {
                if (!accountIdByChangedStage.containsKey(opportunity.AccountId)) {
                    accountIdByChangedStage.put(opportunity.AccountId, new Map<String, String>());
                }
                accountIdByChangedStage.get(opportunity.AccountId).put(opportunity.Service_Type__c, opportunity.StageName);
            }
        }

        if (!accountIdByChangedStage.isEmpty()) {
            OpportunityService.updateProductStatusOnAccount(accountIdByChangedStage);
        }
    }

}