force-app/main/core/objects/Noda_Custom_Settings__c/Noda_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Noda Custom Settings</label>
</CustomObject>

force-app/main/core/objects/Noda_Custom_Settings__c/fields/Org_URL__c.field-meta.xml
<CustomField>
    <fullName>Org_URL__c</fullName>
    <label>Org URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NodaLetterController.cls
public class NodaLetterController {

    public string getStrLogoUrl() {
        return getUrlByDocumentName('NodaLogo');
    }

    public String getUrlByDocumentName(String nameOfDocument) {
        String urlOfLogo = null;

        for(Document logo: [SELECT Id FROM Document WHERE DeveloperName = :nameOfDocument LIMIT 1]){

            String idOfOrganization = UserInfo.getOrganizationId();
            Noda_Custom_Settings__c nodaCustomSettings = Noda_Custom_Settings__c.getOrgDefaults();
            String urlOfOrg = '/';
            if(nodaCustomSettings != null && nodaCustomSettings.Org_URL__c!=null) {
                urlOfOrg = nodaCustomSettings.Org_URL__c;
            }

            urlOfLogo = urlOfOrg + 'servlet/servlet.ImageServer?id=' + logo.Id + '&oid=' + idOfOrganization;
        }
        System.debug('urlOfLogo ' + urlOfLogo);
        return urlOfLogo;
    }
}