force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/General_Traffic__c.field-meta.xml
<CustomField>
    <fullName>General_Traffic__c</fullName>
    <label>General Traffic</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/core/objects/Lead/fields/GEOText__c.field-meta.xml
<CustomField>
    <fullName>GEOText__c</fullName>
    <label>Supported GEO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Other_GEO__c.field-meta.xml
<CustomField>
    <fullName>Other_GEO__c</fullName>
    <label>Other GEO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrefferedServices__c.field-meta.xml
<CustomField>
    <fullName>PrefferedServices__c</fullName>
    <label>Preffered Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Banking</fullName>
            </value>
            <value>
                <fullName>Cards Processing</fullName>
            </value>
            <value>
                <fullName>Pay by Link</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Banking Pay-ins</fullName>
            </value>
            <value>
                <fullName>Open Banking Pay-outs</fullName>
            </value>
            <value>
                <fullName>Pay by Link</fullName>
            </value>
            <value>
                <fullName>Noda GO</fullName>
            </value>
            <value>
                <fullName>Cards Processing</fullName>
            </value>
            <value>
                <fullName>Interac Canada</fullName>
            </value>
            <value>
                <fullName>Pix Brazil</fullName>
            </value>
            <value>
                <fullName>Other (Specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/objects/Lead/fields/Traffic__c.field-meta.xml
<CustomField>
    <fullName>Traffic__c</fullName>
    <label>Supported GEO Traffic</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler {
    
    public void onAfterInsert( List<Lead> listOfLeads){

        Set<Id> setOfIds = new Set<Id>();
        
        for(Lead lead : listOfLeads) {
            if(lead.Website != null) {
                setOfIds.add(lead.Id);
            }
        }
        if(!setOfIds.isEmpty()) {
            updateIndustryOfLead(setOfIds);
            updateTrafficOfLead(setOfIds);
        }
    }


    public void onBeforeInsert( List<Lead> listOfLeads){

        for(Lead lead : listOfLeads) {

            if((lead.PrefferedServices__c != null && lead.PrefferedServices__c.contains('Cards Processing')) || (lead.Product__c != null && lead.Product__c.contains('Cards Processing'))) {
                lead.Lead_with_Card_Process__c = true;
            }
        }
       
    }
    

    public void onBeforeUpdate(Map<Id,Lead> oldMap, Map<Id,Lead> newMap){
        
        Set<Id> setOfIds = new Set<Id>();
        for(Lead lead : newMap.values()) {
            if(lead.Website != oldMap.get(lead.Id).Website && (lead.Website != null ||  lead.Website != '')) {
                setOfIds.add(lead.Id);
            }
        }
        if(!setOfIds.isEmpty()) {
            updateIndustryOfLead(setOfIds);
            updateTrafficOfLead(setOfIds);
        }
    }

    @future(callout=true)
    public static void updateIndustryOfLead(Set<Id> leadIds) {
        
        List<Lead> leadsToUpdate = new List<Lead>();

        for (Lead lead : [SELECT Id, Website, Industry__c FROM Lead WHERE Id IN :leadIds]) {
                String industry = SimilarWebRestApiService.getIndustryOfWebsite(getCorrectLinkOfWebsite(lead.Website));
                lead.Industry__c = industry;
                leadsToUpdate.add(lead);
        }
        if (!leadsToUpdate.isEmpty()) {
            update leadsToUpdate;
        }
    }

    @future(callout=true)
    public static void updateTrafficOfLead(Set<Id> leadIds) {
        
        List<Lead> leadsToUpdate = new List<Lead>();
        Map<String, String> mapOfSupportedCountryCodeByName = getCountryCodeOfSupportedCountries(true);
        Map<String, String> mapOfUnsupportedCountryCodeByName = getCountryCodeOfSupportedCountries(false);

        for (Lead lead : [SELECT Id, Website, Industry__c FROM Lead WHERE Id IN :leadIds]) {
                Map<String, String> mapOfTrafficByCountryCode = SimilarWebRestApiService.getCountryAndTrafficFromWebsite(getCorrectLinkOfWebsite(lead.Website), mapOfSupportedCountryCodeByName, mapOfUnsupportedCountryCodeByName);
                    lead.GEOText__c = mapOfTrafficByCountryCode.get('valueOfSupportedGeoField');
                    lead.Traffic__c = mapOfTrafficByCountryCode.get('valueOfSupportedTraffic') != null ? Decimal.valueOf(mapOfTrafficByCountryCode.get('valueOfSupportedTraffic')) : 0;
                    lead.Other_GEO__c = mapOfTrafficByCountryCode.get('valueOfUnsupportedGeoField');
                    lead.General_Traffic__c =  mapOfTrafficByCountryCode.get('valueOfGeneralTraffic') != null ? Decimal.valueOf(mapOfTrafficByCountryCode.get('valueOfGeneralTraffic')) : 0;

                leadsToUpdate.add(lead);
        }
        if (!leadsToUpdate.isEmpty()) {
            update leadsToUpdate;
        }
    }

    private static Map<String, String> getCountryCodeOfSupportedCountries(Boolean isCountryWithSupportedBankd) {
        
        Map<String, String> mapOfCountryCodeByName = new Map<String, String> ();
        List<Country__c> listOfCountries = [SELECT Name, Country_Code__c FROM Country__c WHERE Is_country_with_supported_banks__c = :isCountryWithSupportedBankd];

        if(!listOfCountries.isEmpty()) {
            for(Country__c country : listOfCountries) {
                mapOfCountryCodeByName.put(country.Name, country.Country_Code__c);
            }
        }

        return mapOfCountryCodeByName;
    }

    private static String getCorrectLinkOfWebsite(String urlOfWebsite) {

        String urlOfWebsiteToLowerCase = urlOfWebsite.toLowerCase();
        
        Integer indexOfThreeW = urlOfWebsiteToLowerCase.indexOf('www.');
        String urlForSimilarweb = '';

        if (indexOfThreeW != -1) {
            urlForSimilarweb = urlOfWebsiteToLowerCase.substring(indexOfThreeW + 4);
        } else {
            urlForSimilarweb = urlOfWebsiteToLowerCase;
        }

        if (urlForSimilarweb.endsWith('/')) {
            urlForSimilarweb = urlForSimilarweb.substring(0, urlForSimilarweb.length() - 1);
        }
        return urlForSimilarweb;
    }
}