force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/General_Traffic__c.field-meta.xml
<CustomField>
    <fullName>General_Traffic__c</fullName>
    <label>General Traffic</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/core/objects/Lead/fields/GEOText__c.field-meta.xml
<CustomField>
    <fullName>GEOText__c</fullName>
    <label>Supported GEO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Other_GEO__c.field-meta.xml
<CustomField>
    <fullName>Other_GEO__c</fullName>
    <label>Other GEO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/core/objects/Lead/fields/Traffic__c.field-meta.xml
<CustomField>
    <fullName>Traffic__c</fullName>
    <label>Supported GEO Traffic</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/tests/async/UpdateLeadsBatchTest.cls
@IsTest
private class UpdateLeadsBatchTest {
    private static final Integer numberOfRecords = LeadTriggerHandler.batchSize;

    @isTest
    public static void updateLeads() {
        Test.setMock(HttpCalloutMock.class, new SimilarWebRestApiServiceMock());
        Set<Id> setOfIds = new Set<Id>();
        List<Country__c> listOfCountries = new List<Country__c>();

        listOfCountries.add(TestDataFactory.initCountry(TestConstants.FRANCE_COUNTRY_NAME, TestConstants.FRANCE_COUNTRY_CODE, true, false));
        listOfCountries.add(TestDataFactory.initCountry(TestConstants.US_COUNTRY_NAME, TestConstants.US_COUNTRY_CODE, false, false));

        insert listOfCountries;

        List<Lead> testLeads = TestDataFactory.initLeads(numberOfRecords, null, null, false);

        insert testLeads;

        for (Lead lead : testLeads) {
            setOfIds.add(lead.Id);
        }

        UpdateLeadsBatch updateLeadsBatch = new UpdateLeadsBatch(setOfIds);
        Test.startTest();
        Id batchProcessId = Database.executeBatch(updateLeadsBatch);
        Test.stopTest();

        List<Lead> updatedLeads = [SELECT Id, Industry__c, GEOText__c, Traffic__c, Other_GEO__c, General_Traffic__c FROM Lead];

        AsyncApexJob jobResult = [SELECT NumberOfErrors, Status FROM AsyncApexJob WHERE Id = :batchProcessId];

        Assert.areEqual(numberOfRecords, updatedLeads.size());
        Assert.areEqual(0, jobResult.NumberOfErrors);
        Assert.areEqual(ConstantUtility.COMPLETED_STATUS, jobResult.Status);

        for (Lead lead : updatedLeads) {
            Assert.areEqual(lead.Industry__c, TestConstants.SOME_CATEGORY_LEAD_INDUSTRY);
            Assert.isTrue(lead.GEOText__c.contains(TestConstants.FRANCE_COUNTRY_CODE));
            Assert.areEqual(lead.Traffic__c, TestConstants.FRANCE_VISITS);
            Assert.isTrue(lead.Other_GEO__c.contains(TestConstants.US_COUNTRY_CODE));
            Assert.areEqual(lead.General_Traffic__c, TestConstants.FRANCE_VISITS + TestConstants.US_VISITS);
        }
    }
}