force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/General_Traffic__c.field-meta.xml
<CustomField>
    <fullName>General_Traffic__c</fullName>
    <label>General Traffic</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/core/objects/Lead/fields/GEOText__c.field-meta.xml
<CustomField>
    <fullName>GEOText__c</fullName>
    <label>Supported GEO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Other_GEO__c.field-meta.xml
<CustomField>
    <fullName>Other_GEO__c</fullName>
    <label>Other GEO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrefferedServices__c.field-meta.xml
<CustomField>
    <fullName>PrefferedServices__c</fullName>
    <label>Preffered Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Banking</fullName>
            </value>
            <value>
                <fullName>Cards Processing</fullName>
            </value>
            <value>
                <fullName>Pay by Link</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Banking Pay-ins</fullName>
            </value>
            <value>
                <fullName>Open Banking Pay-outs</fullName>
            </value>
            <value>
                <fullName>Pay by Link</fullName>
            </value>
            <value>
                <fullName>Noda GO</fullName>
            </value>
            <value>
                <fullName>Cards Processing</fullName>
            </value>
            <value>
                <fullName>Interac Canada</fullName>
            </value>
            <value>
                <fullName>Pix Brazil</fullName>
            </value>
            <value>
                <fullName>Other (Specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/objects/Lead/fields/Traffic__c.field-meta.xml
<CustomField>
    <fullName>Traffic__c</fullName>
    <label>Supported GEO Traffic</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/tests/triggerHahdlers/LeadTriggerHandlerTest.cls
@isTest
public class LeadTriggerHandlerTest {
    private static final Integer numberOfRecords = LeadTriggerHandler.batchSize;

    @isTest
    public static void beforeInsertPreferredServicesIsNotNull() {
        Test.setMock(HttpCalloutMock.class, new SimilarWebRestApiServiceMock());
        List<Lead> testLeads = new List<Lead>();

        testLeads.addAll(TestDataFactory.initLeads(numberOfRecords, ConstantUtility.CARDS_PROCESSING, null, false));

        Test.startTest();
        insert testLeads;
        Test.stopTest();

        List<Lead> newLeads = [SELECT Lead_with_Card_Process__c FROM Lead WHERE Id IN :testLeads];

        Assert.areEqual(numberOfRecords, newLeads.size());

        for (Lead newLead : newLeads) {
            Assert.areEqual(true, newLead.Lead_with_Card_Process__c);
        }
    }

    @isTest
    public static void beforeInsertPreferredServicesAndProductIsNotNull() {
        Test.setMock(HttpCalloutMock.class, new SimilarWebRestApiServiceMock());
        List<Lead> testLeads = new List<Lead>();

        testLeads.addAll(TestDataFactory.initLeads(numberOfRecords, ConstantUtility.CARDS_PROCESSING, ConstantUtility.OPEN_BANKING_PAY_INS, false));

        Test.startTest();
        insert testLeads;
        Test.stopTest();

        List<Lead> newLeads = [SELECT Lead_with_Card_Process__c FROM Lead WHERE Id IN :testLeads];

        Assert.areEqual(numberOfRecords, newLeads.size());

        for (Lead newLead : newLeads) {
            Assert.areEqual(true, newLead.Lead_with_Card_Process__c);
        }
    }

    @isTest
    public static void beforeInsertPreferredServicesAndProductIsNull() {
        Test.setMock(HttpCalloutMock.class, new SimilarWebRestApiServiceMock());
        List<Lead> testLeads = new List<Lead>();

        testLeads.addAll(TestDataFactory.initLeads(numberOfRecords, null, null, false));

        Test.startTest();
        insert testLeads;
        Test.stopTest();

        List<Lead> newLeads = [SELECT Lead_with_Card_Process__c FROM Lead WHERE Id IN :testLeads];

        Assert.areEqual(numberOfRecords, newLeads.size());

        for (Lead newLead : newLeads) {
            Assert.areEqual(false, newLead.Lead_with_Card_Process__c);
        }
    }

    @isTest
    public static void afterInsertWebsiteIsNull() {
        Test.setMock(HttpCalloutMock.class, new SimilarWebRestApiServiceMock());
        List<Lead> testLeads = TestDataFactory.initLeads(numberOfRecords, null, null, false);

        for (Lead lead : testLeads) {
            lead.Website = null;
        }

        Test.startTest();
        insert testLeads;
        Test.stopTest();

        List<Lead> updatedLeads = [SELECT Id, GEOText__c, Traffic__c, Other_GEO__c, General_Traffic__c, Industry__c FROM Lead];

        Assert.areEqual(numberOfRecords, updatedLeads.size());

        for (Lead newLead : updatedLeads) {
            Assert.isNull(newLead.Industry__c);
            Assert.isNull(newLead.GEOText__c);
            Assert.isNull(newLead.Traffic__c);
            Assert.isNull(newLead.Other_GEO__c);
            Assert.isNull(newLead.General_Traffic__c);
        }
    }

    @isTest
    public static void testOnAfterInsert() {
        Test.setMock(HttpCalloutMock.class, new SimilarWebRestApiServiceMock());
        List<Lead> testLeads = TestDataFactory.initLeads(numberOfRecords, null, null, false);

        List<Country__c> listOfCountries = new List<Country__c>();
        listOfCountries.add(TestDataFactory.initCountry(TestConstants.FRANCE_COUNTRY_NAME, TestConstants.FRANCE_COUNTRY_CODE, true, false));
        listOfCountries.add(TestDataFactory.initCountry(TestConstants.US_COUNTRY_NAME, TestConstants.US_COUNTRY_CODE, false, false));

        insert listOfCountries;


        Test.startTest();
        insert testLeads;
        Test.stopTest();

        List<Lead> updatedLeads = [SELECT Id, Industry__c, Product__c, PrefferedServices__c FROM Lead];
        for (Lead lead : updatedLeads) {
            Assert.isNotNull(lead.Industry__c);
            Assert.isNull(lead.PrefferedServices__c);
            Assert.isNull(lead.Product__c);
        }
    }

    @isTest
    public static void testOnBeforeUpdate() {
        Test.setMock(HttpCalloutMock.class, new SimilarWebRestApiServiceMock());
        List<Lead> testLeads = TestDataFactory.initLeads(numberOfRecords, null, null, false);

        for (Lead lead : testLeads) {
            lead.Website = null;
        }

        insert testLeads;

        List<Country__c> listOfCountries = new List<Country__c>();
        listOfCountries.add(TestDataFactory.initCountry(TestConstants.FRANCE_COUNTRY_NAME, TestConstants.FRANCE_COUNTRY_CODE, true, false));
        listOfCountries.add(TestDataFactory.initCountry(TestConstants.US_COUNTRY_NAME, TestConstants.US_COUNTRY_CODE, false, false));

        insert listOfCountries;

        for (Lead lead : testLeads) {
            lead.Website = 'www.example' + testLeads.indexOf(lead) + '.com';
        }

        Test.startTest();
        update testLeads;
        Test.stopTest();

        List<Lead> updatedLeads = [SELECT Id, Industry__c, GEOText__c, Traffic__c, Other_GEO__c, General_Traffic__c FROM Lead];
        for (Lead lead : updatedLeads) {
            Assert.areEqual(lead.Industry__c, TestConstants.SOME_CATEGORY_LEAD_INDUSTRY);
            Assert.isTrue(lead.GEOText__c.contains(TestConstants.FRANCE_COUNTRY_CODE));
            Assert.areEqual(lead.Traffic__c, TestConstants.FRANCE_VISITS);
            Assert.isTrue(lead.Other_GEO__c.contains(TestConstants.US_COUNTRY_CODE));
            Assert.areEqual(lead.General_Traffic__c, TestConstants.FRANCE_VISITS + TestConstants.US_VISITS);
        }
    }

    @isTest
    public static void testOnBeforeUpdateWithoutCountries() {
        Test.setMock(HttpCalloutMock.class, new SimilarWebRestApiServiceMock());
        List<Lead> testLeads = TestDataFactory.initLeads(numberOfRecords, null, null, false);

        for (Lead lead : testLeads) {
            lead.Website = null;
        }

        insert testLeads;

        Test.setMock(HttpCalloutMock.class, new SimilarWebRestApiServiceMock());

        for (Lead lead : testLeads) {
            lead.Website = 'www.example' + testLeads.indexOf(lead) + '.com';
        }

        Test.startTest();
        update testLeads;
        Test.stopTest();

        List<Lead> updatedLeads = [SELECT Id, Industry__c, GEOText__c, Traffic__c, Other_GEO__c, General_Traffic__c FROM Lead];

        for (Lead lead : updatedLeads) {
            Assert.areEqual(lead.Industry__c, TestConstants.SOME_CATEGORY_LEAD_INDUSTRY);
            Assert.areEqual(lead.Traffic__c, 0);
            Assert.areEqual(lead.General_Traffic__c, TestConstants.FRANCE_VISITS + TestConstants.US_VISITS);
        }
    }
}