force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Incorporation_Country_Score__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_Country_Score__c</fullName>
    <formula>CASE( 
    Prohibited__c, 
    &apos;Prohibited&apos;, 30, 
    IF(
        AND(Score__c &gt;= 80, Score__c &lt;= 100),
        2,
        IF(
            AND(Score__c &gt;= 70, Score__c &lt; 80),
            3,
            IF(
                AND(Score__c &gt;= 60, Score__c &lt; 70),
                5,
                IF(
                    AND(Score__c &gt;= 50, Score__c &lt; 60),
                    6,
                    IF(Score__c = 50, 9, null)
                )
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incorporation Country Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/UBO_Citizenship_Score__c.field-meta.xml
<CustomField>
    <fullName>UBO_Citizenship_Score__c</fullName>
    <formula>CASE( 
    Prohibited__c, 
    &apos;Prohibited&apos;, 30, 
    IF(
        AND(Score__c &gt;= 80, Score__c &lt;= 100),
        2,
        IF(
            AND(Score__c &gt;= 70, Score__c &lt; 80),
            3,
            IF(
                AND(Score__c &gt;= 60, Score__c &lt; 70),
                5,
                IF(
                    AND(Score__c &gt;= 50, Score__c &lt; 60),
                    6,
                    IF(Score__c = 50, 9, null)
                )
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UBO Citizenship Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/UBO_Nationality_Score__c.field-meta.xml
<CustomField>
    <fullName>UBO_Nationality_Score__c</fullName>
    <formula>CASE( 
    Prohibited__c, 
    &apos;Prohibited&apos;, 9, 
    IF(
        AND(Score__c &gt;= 80, Score__c &lt;= 100),
        2,
        IF(
            AND(Score__c &gt;= 70, Score__c &lt; 80),
            3,
            IF(
                AND(Score__c &gt;= 60, Score__c &lt; 70),
                5,
                IF(
                    AND(Score__c &gt;= 50, Score__c &lt; 60),
                    6,
                    IF(Score__c = 50, 9, null)
                )
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UBO Nationality Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/UBO_Residence_Score__c.field-meta.xml
<CustomField>
    <fullName>UBO_Residence_Score__c</fullName>
    <formula>CASE( 
    Prohibited__c, 
    &apos;Prohibited&apos;, 30, 
    IF(
        AND(Score__c &gt;= 80, Score__c &lt;= 100),
        2,
        IF(
            AND(Score__c &gt;= 70, Score__c &lt; 80),
            3,
            IF(
                AND(Score__c &gt;= 60, Score__c &lt; 70),
                5,
                IF(
                    AND(Score__c &gt;= 50, Score__c &lt; 60),
                    6,
                    IF(Score__c = 50, 9, null)
                )
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UBO Residence Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/core/classes/selectors/CountrySelector.cls
public inherited sharing class CountrySelector {
    public static List<Country__c> getCountries() {
        return  [
            SELECT Name, Incorporation_Country_Score__c, UBO_Citizenship_Score__c, UBO_Nationality_Score__c, UBO_Residence_Score__c
            FROM Country__c
            ORDER BY Name
        ];
    }

    public static List<Country__c> getCountriesForSimilarWebCall() {
        return  [
            SELECT Name, Country_Code__c, Is_country_with_supported_banks__c
            FROM Country__c
            ORDER BY Name
        ];
    }
}