force-app/main/core/objects/Account/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <label>Activity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/core/objects/Account/fields/OwnerFullName__c.field-meta.xml
<CustomField>
    <fullName>OwnerFullName__c</fullName>
    <formula>Owner.FirstName + &quot; &quot; + Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner full name</label>
    <type>Text</type>
</CustomField>

force-app/main/core/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not in live</fullName>
                <default>true</default>
                <label>Not in live</label>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <color>#FF0000</color>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Closed lost</fullName>
                <color>#FF0000</color>
                <label>Closed lost</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/classes/selectors/AccountSelector.cls
public inherited sharing class AccountSelector {
    public static List<Account> getAccounts(Set<Id> setOfAccountIds) {
        return [
            SELECT Id, Name, OwnerId
            FROM Account
            WHERE Id IN :setOfAccountIds
        ];
    }

    public static Account getAccount(Id accountId) {
        return [
            SELECT Id, Name, OwnerId
            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];
    }

    public static List<Account> getAccountRows(String searchKey) {
        return [
            SELECT Id, Name, Industry, OwnerFullName__c, Website, Status__c, Activity_Date__c
            FROM Account
            WHERE Name LIKE :searchKey
            OR Website LIKE :searchKey
        ];
    }

    public static List<Account> getAccountActivityDate(Set<Id> setOfAccountIds) {
        return [
            SELECT Id, Activity_Date__c 
            FROM Account 
            WHERE Id IN :setOfAccountIds
        ];
    }
}