force-app/main/core/objects/Account/fields/Cards__c.field-meta.xml
<CustomField>
    <fullName>Cards__c</fullName>
    <label>Cards</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/KYW__c.field-meta.xml
<CustomField>
    <fullName>KYW__c</fullName>
    <label>KYW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/New_Comment__c.field-meta.xml
<CustomField>
    <fullName>New_Comment__c</fullName>
    <label>New comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/core/objects/Account/fields/Noda_Buffet__c.field-meta.xml
<CustomField>
    <fullName>Noda_Buffet__c</fullName>
    <label>Noda Buffet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Noda_Go__c.field-meta.xml
<CustomField>
    <fullName>Noda_Go__c</fullName>
    <label>Noda Go</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Pay_In__c.field-meta.xml
<CustomField>
    <fullName>Pay_In__c</fullName>
    <label>Pay In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Pay_Out__c.field-meta.xml
<CustomField>
    <fullName>Pay_Out__c</fullName>
    <label>Pay Out</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Payment_links__c.field-meta.xml
<CustomField>
    <fullName>Payment_links__c</fullName>
    <label>Payment links</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Previous_comment__c.field-meta.xml
<CustomField>
    <fullName>Previous_comment__c</fullName>
    <label>Previous comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/core/objects/Account/fields/Previous_owner__c.field-meta.xml
<CustomField>
    <fullName>Previous_owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/core/objects/Account/fields/Trusted_Payments__c.field-meta.xml
<CustomField>
    <fullName>Trusted_Payments__c</fullName>
    <label>Trusted Payments</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/globalValueSets/Opportunity_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Ready For Live</fullName>
    </customValue>
    <customValue>
        <fullName>In Live</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <masterLabel>Opportunity Status</masterLabel>
</GlobalValueSet>

force-app/main/core/classes/triggerHandlers/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler extends TriggerHandler {
    private static final List<String> fieldsToCompare = new List<String>{
        'Pay_In__c', 'Pay_Out__c', 'Noda_Go__c', 'Noda_Buffet__c',
        'Payment_links__c', 'Trusted_Payments__c', 'Cards__c', 'KYW__c'
    };

    public override void afterInsert() {
        Set<Id> setOfIds = new Set<Id>();

        for (Account account : (List<Account>) Trigger.new) {
            setOfIds.add(account.Id);
        }

        if (!setOfIds.isEmpty()) {
            AccountService.createOpportunitiesForAccount(setOfIds);
        }
    }

    public override void beforeUpdate() {
        Map<Id, Account> oldMap = (Map<Id, Account>) Trigger.oldMap;
        Map<Id, Account> newMap = (Map<Id, Account>) Trigger.newMap;

        for (Account account : newMap.values()) {
            if (account.New_Comment__c != oldMap.get(account.Id).New_Comment__c && oldMap.get(account.Id).New_Comment__c != null) {
                account.Previous_comment__c = oldMap.get(account.Id).New_Comment__c;
            }
            if (account.OwnerId != oldMap.get(account.Id).OwnerId) {
                account.Previous_owner__c = oldMap.get(account.Id).OwnerId;
            }
        }

    }

    public override void afterUpdate() {
        Map<Id, Account> oldMap = (Map<Id, Account>) Trigger.oldMap;
        Map<Id, Account> newMap = (Map<Id, Account>) Trigger.newMap;
        Set<Id> setOfUpdatedAccountIds = new Set<Id>();
        Map<Account, List<String>> listOfAccountsWithFieldsToUpdate = new Map<Account, List<String>>();

        for (Account account : newMap.values()) {
            List<String> updatedFields = new List<String>();

            if (account.OwnerId != oldMap.get(account.Id).OwnerId) {
                setOfUpdatedAccountIds.add(account.Id);
            }
            for (String field : fieldsToCompare) {
                if (account.get(field) != oldMap.get(account.Id).get(field)) {
                    updatedFields.add(field);
                }
            }
            if (!updatedFields.isEmpty()) {
                listOfAccountsWithFieldsToUpdate.put(account, updatedFields);
            }
        }

        if (!setOfUpdatedAccountIds.isEmpty()) {
            setOfUpdatedAccountIds = AccountService.getAccountsWithFirstOwnerUpdate(setOfUpdatedAccountIds);

            if (!setOfUpdatedAccountIds.isEmpty()) {
                AccountService.changeOpportunitiesOwner(setOfUpdatedAccountIds);
            }
        }

        if (!listOfAccountsWithFieldsToUpdate.isEmpty()) {
            AccountService.updateOpportunities(listOfAccountsWithFieldsToUpdate);
        }
    }
}