force-app/main/core/objects/Account/fields/Cards__c.field-meta.xml
<CustomField>
    <fullName>Cards__c</fullName>
    <label>Cards</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/KYW__c.field-meta.xml
<CustomField>
    <fullName>KYW__c</fullName>
    <label>KYW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Noda_Buffet__c.field-meta.xml
<CustomField>
    <fullName>Noda_Buffet__c</fullName>
    <label>Noda Buffet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Noda_Go__c.field-meta.xml
<CustomField>
    <fullName>Noda_Go__c</fullName>
    <label>Noda Go</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Pay_In__c.field-meta.xml
<CustomField>
    <fullName>Pay_In__c</fullName>
    <label>Pay In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Pay_Out__c.field-meta.xml
<CustomField>
    <fullName>Pay_Out__c</fullName>
    <label>Pay Out</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Payment_links__c.field-meta.xml
<CustomField>
    <fullName>Payment_links__c</fullName>
    <label>Payment links</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Trusted_Payments__c.field-meta.xml
<CustomField>
    <fullName>Trusted_Payments__c</fullName>
    <label>Trusted Payments</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Noda_Custom_Settings__c/Noda_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Noda Custom Settings</label>
</CustomObject>

force-app/main/core/objects/Noda_Custom_Settings__c/fields/Upsale_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Upsale_Opportunity__c</fullName>
    <label>Upsale Opportunity</label>
    <type>TextArea</type>
</CustomField>

force-app/main/core/objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Noda Go</fullName>
            </value>
            <value>
                <fullName>Noda Buffet</fullName>
            </value>
            <value>
                <fullName>Pay In</fullName>
            </value>
            <value>
                <fullName>Pay Out</fullName>
            </value>
            <value>
                <fullName>Payment links</fullName>
            </value>
            <value>
                <fullName>Trusted Payments</fullName>
            </value>
            <value>
                <fullName>Cards</fullName>
            </value>
            <value>
                <fullName>KYW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/objects/Opportunity/recordTypes/Upsale.recordType-meta.xml
<RecordType>
    <fullName>Upsale</fullName>
    <active>true</active>
    <businessProcess>Upsale</businessProcess>
    <label>Upsale</label>
</RecordType>

force-app/main/core/globalValueSets/Opportunity_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Ready For Live</fullName>
    </customValue>
    <customValue>
        <fullName>In Live</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <masterLabel>Opportunity Status</masterLabel>
</GlobalValueSet>

force-app/main/core/classes/services/AccountService.cls
public with sharing class AccountService {
    public static OpportunityUtils oppUtilsCls {
        get {
            if (oppUtilsCls == null) {
                oppUtilsCls = new OpportunityUtils();
            }

            return oppUtilsCls;
        }
        set;
    }

    public static void createOpportunitiesForAccount(Set<Id> setOfCreatedAccounts) {
        List<Opportunity> listOfOpportunitiesToInsert = new List<Opportunity>();
        Noda_Custom_Settings__c settingsOfNoda = SettingUtils.settingsOfNoda;
        List<String> listOfUpsaleOpportunities = settingsOfNoda.Upsale_Opportunity__c.split(',');

        Map<String, Id> recordTypeNameToId = RecordTypeSelector.getRecordTypeNameToId(new List<String>{
            ConstantUtility.UPSALE
        });

        List<Account> listOfAccount = AccountSelector.getAccounts(setOfCreatedAccounts);

        for (Account account : listOfAccount) {
            listOfOpportunitiesToInsert.addAll(initOpportunityForProduct(listOfUpsaleOpportunities, account, ConstantUtility.NEGOTIATION, recordTypeNameToId.get(ConstantUtility.UPSALE)));
        }

        insert listOfOpportunitiesToInsert;
    }

    public static void changeOpportunitiesOwner(Set<Id> setOfUpdatedAccountIds) {
        List<Opportunity> listOfOpportunitiesToUpdate = new List<Opportunity>();

        List<Account> listOfAccounts = AccountSelector.getAccounts(setOfUpdatedAccountIds);
        List<Opportunity> listOfOpportunities = OpportunitySelector.getOpportunitiesByAcocunt(setOfUpdatedAccountIds);

        for(Account account : listOfAccounts) {
            for(Opportunity opportunity : listOfOpportunities) {
                if (account.Id == opportunity.AccountId) {
                    listOfOpportunitiesToUpdate.add(oppUtilsCls.updateOpportunityOwner(opportunity, account.OwnerId));
                }
            }
        }
        update listOfOpportunitiesToUpdate;
    }
    
    public static Set<Id> getAccountsWithFirstOwnerUpdate(Set<Id> setOfUpdatedAccountIds) {
        List<AccountHistory> listOfAccountHistory = AccountHistorySelector.getAccountHistory(setOfUpdatedAccountIds);

        for (AccountHistory accountHistory : listOfAccountHistory) {
            if (setOfUpdatedAccountIds.contains(accountHistory.AccountId)) {
                setOfUpdatedAccountIds.remove(accountHistory.AccountId);
            }
        }

        return setOfUpdatedAccountIds;
    }

    public static void updateOpportunities(Map<Account, List<String>> listOfAccountsWithFieldsToUpdate) {
        List<Opportunity> listOfOpportunitiesToUpdate = new List<Opportunity>();
        Map<String, SObjectField> serviceTypeFieldMap = new Map<String, SObjectField>{
            'Pay In' => Account.Pay_In__c,
            'Pay Out' => Account.Pay_Out__c,
            'Noda Go' => Account.Noda_Go__c,
            'Noda Buffet' => Account.Noda_Buffet__c,
            'Payment links' => Account.Payment_links__c,
            'Trusted Payments' => Account.Trusted_Payments__c,
            'Cards' => Account.Cards__c,
            'KYW' => Account.KYW__c
        };
    
        Set<Id> setOfAccountIds = new Set<Id>();
        for (Account account : listOfAccountsWithFieldsToUpdate.keySet()) {
            setOfAccountIds.add(account.Id);
        }
    
        Map<String, List<Opportunity>> serviceTypeOpportunitiesMap = new Map<String, List<Opportunity>>();
        for (String serviceType : serviceTypeFieldMap.keySet()) {
            serviceTypeOpportunitiesMap.put(serviceType, new List<Opportunity>());
        }
    
        for (Opportunity opportunity : [SELECT Id, Service_Type__c, StageName, AccountId FROM Opportunity WHERE AccountId IN :setOfAccountIds]) {
            String serviceType = opportunity.Service_Type__c;
            if (serviceTypeFieldMap.containsKey(serviceType)) {
                serviceTypeOpportunitiesMap.get(serviceType).add(opportunity);
            }
        }
    
        for (Account account : listOfAccountsWithFieldsToUpdate.keySet()) {
            List<String> updatedFields = listOfAccountsWithFieldsToUpdate.get(account);
            
            for (String updatedField : updatedFields) {
                String serviceType = getFieldServiceType(updatedField, serviceTypeFieldMap);
                SObjectField field = serviceTypeFieldMap.get(serviceType);
                List<Opportunity> opportunities = serviceTypeOpportunitiesMap.get(serviceType);
    
                for (Opportunity opportunity : opportunities) {
                    if (account.Id == opportunity.AccountId) {
                        opportunity.StageName = (String) account.get(field);
                        listOfOpportunitiesToUpdate.add(opportunity);
                    }
                }
            }
        }
        System.debug('listOfOpportunitiesToUpdate ' + listOfOpportunitiesToUpdate);
        update listOfOpportunitiesToUpdate;
    }

    private static String getFieldServiceType(String fieldName, Map<String, SObjectField> serviceTypeFieldMap) {
        for (String serviceType : serviceTypeFieldMap.keySet()) {
            if (serviceTypeFieldMap.get(serviceType).getDescribe().getName() == fieldName) {
                return serviceType;
            }
        }
        return null;
    }
    

    private static List<Opportunity> initOpportunityForProduct(List<String> typeOpportunities, Account account, String stage, Id recordTypeId) {
        List<Opportunity> opportunities = new List<Opportunity>();
        Date closeDate = Date.today().addMonths(1);

        for (String product : typeOpportunities) {
            String name = account.Name + ' - ' + product;
            opportunities.add(OpportunityUtils.createOpportunity(name, account.Id, account.OwnerId, stage, closeDate, recordTypeId, product));
        }

        return opportunities;
    }
}