force-app/main/core/objects/Account/fields/Noda_Buffet__c.field-meta.xml
<CustomField>
    <fullName>Noda_Buffet__c</fullName>
    <label>Noda Buffet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/objects/Account/fields/Noda_Go__c.field-meta.xml
<CustomField>
    <fullName>Noda_Go__c</fullName>
    <label>Noda Go</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/core/globalValueSets/Opportunity_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Meeting</fullName>
    </customValue>
    <customValue>
        <fullName>Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Ready For Live</fullName>
    </customValue>
    <customValue>
        <fullName>In Live</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <masterLabel>Opportunity Status</masterLabel>
</GlobalValueSet>

force-app/main/tests/triggerHahdlers/OpportunityTriggerHandlerTest.cls
@IsTest
private class OpportunityTriggerHandlerTest {
    private static final Integer NEW_RECORDS = TestConstants.NEW_RECORDS;

    @TestSetup
    static void testSetup() {
        TestDataFactory.createNodaCustomSetting();
    }

    @IsTest
    static void afterUpdateWhenStageChanged() {
        TriggerHandler.bypass(AccountTriggerHandler.class.getName());

        List<Account> accounts = TestDataFactory.createAccounts(true, NEW_RECORDS);
        List<Opportunity> opportunities = TestDataFactory.createOpportunities(true, accounts);
        List<Opportunity> updOpportunities = new List<Opportunity>();
        Boolean isError = false;

        for (Opportunity opp : opportunities) {
            if (opp.Name.contains('Noda Go') || opp.Name.contains('Noda Buffet')) {
                opp.StageName = TestConstants.TEST_STAGE;
                updOpportunities.add(opp);
            }
        }
        try {
            Test.startTest();
            update updOpportunities;
            Test.stopTest();
        } catch (Exception e) {
            System.debug(e.getMessage());
            isError = true;  
        }

        List<Account> result = [SELECT Id, Noda_Go__c, Noda_Buffet__c FROM Account WHERE Id IN :accounts AND Noda_Go__c = :TestConstants.TEST_STAGE AND Noda_Buffet__c = :TestConstants.TEST_STAGE];

        Assert.isFalse(isError);
        Assert.areEqual(NEW_RECORDS, result.size());
        Assert.areEqual(updOpportunities.size(), 400);

    }

}