force-app/main/core/objects/Slack_Configuration__c/Slack_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Slack Configuration</label>
</CustomObject>

force-app/main/core/objects/Slack_Configuration__c/fields/Bot_Token__c.field-meta.xml
<CustomField>
    <fullName>Bot_Token__c</fullName>
    <label>Bot Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/core/objects/Slack_Configuration__c/fields/Channel_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Name__c</fullName>
    <label>Channel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/core/objects/Slack_Configuration__c/fields/Digital_Lead_Channel__c.field-meta.xml
<CustomField>
    <fullName>Digital_Lead_Channel__c</fullName>
    <label>Digital Lead Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/core/objects/Slack_Configuration__c/fields/Post_Message_URL__c.field-meta.xml
<CustomField>
    <fullName>Post_Message_URL__c</fullName>
    <label>Post Message URL</label>
    <type>Url</type>
</CustomField>

force-app/main/core/classes/webServices/SlackNotificationRestService.cls
public with sharing class SlackNotificationRestService {
    public static void sendMessageToSlack(String message) {
        Slack_Configuration__c slackConfig = SettingUtils.slackConfig;

        Map<String, Object> responseData = new Map<String, Object>{
            'channel' => slackConfig.Channel_Name__c,
            'text' => message
        };

        HttpRequest request = setHttpRequest(slackConfig, responseData);

        HttpRequestService.sendRequest(request);
    }

    public static void sendMessageToDigitalLeadSlack(String message) {
        Slack_Configuration__c slackConfig = SettingUtils.slackConfig;

        Map<String, Object> responseData = new Map<String, Object>{
            'channel' => slackConfig.Digital_Lead_Channel__c,
            'text' => message
        };

        HttpRequest request = setHttpRequest(slackConfig, responseData);

        HttpRequestService.sendRequest(request);
    }

    private static HttpRequest setHttpRequest(Slack_Configuration__c slackConfig, Map<String, Object> responseData) {
        HttpRequest request = new HttpRequest();
        request.setEndpoint(slackConfig.Post_Message_URL__c);
        request.setMethod('POST');
        request.setHeader('User-Agent', 'Salesforce');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Authorization', 'Bearer ' + slackConfig.Bot_Token__c);
        request.setBody(JSON.serialize(responseData));

        return request;
    }
}