force-app/main/default/objects/Monitoring__c/Monitoring__c.object-meta.xml
<CustomObject>
    <label>Monitoring</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Monitoring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitorings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring__c/fields/Last_Monitoring_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Monitoring_Date__c</fullName>
    <label>Last Monitoring Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monitoring__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Enhanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring__c/fields/Monitoring_Completed__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Completed__c</fullName>
    <label>Monitoring Completed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monitoring__c/fields/Monitoring_Started_Date__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Started_Date__c</fullName>
    <label>Monitoring Started Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monitoring__c/fields/Monitoring_Status__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Status__c</fullName>
    <label>Monitoring Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Monitoring_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring__c/fields/Next_Monitoring_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Monitoring_Date__c</fullName>
    <label>Next Monitoring Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monitoring__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Periodic KYC review</fullName>
            </value>
            <value>
                <fullName>Merchant Notified</fullName>
            </value>
            <value>
                <fullName>Event/Trigger based</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring__c/fields/Reason_Comment__c.field-meta.xml
<CustomField>
    <fullName>Reason_Comment__c</fullName>
    <label>Reason Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Monitoring__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monitorings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/Monitoring_Type__c.object-meta.xml
<CustomObject>
    <label>Monitoring Type</label>
    <nameField>
        <label>Monitoring Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring_Type__c/fields/Monitoring__c.field-meta.xml
<CustomField>
    <fullName>Monitoring__c</fullName>
    <label>Monitoring</label>
    <referenceTo>Monitoring__c</referenceTo>
    <relationshipLabel>Monitoring Types</relationshipLabel>
    <relationshipName>Monitoring_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Next_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Date__c</fullName>
    <label>Next Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Notify_Before_days__c.field-meta.xml
<CustomField>
    <fullName>Notify_Before_days__c</fullName>
    <label>Notify Before (days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Periodic KYC Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Has not been changed</fullName>
            </value>
            <value>
                <fullName>Has changed</fullName>
            </value>
            <value>
                <fullName>Lower than declared</fullName>
            </value>
            <value>
                <fullName>As expected</fullName>
            </value>
            <value>
                <fullName>Monthly turnover is higher than declared:</fullName>
            </value>
            <value>
                <fullName>Added new</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good Standing Dates</fullName>
            </value>
            <value>
                <fullName>Corporate Doc. Update</fullName>
            </value>
            <value>
                <fullName>Government Doc. Update</fullName>
            </value>
            <value>
                <fullName>UBO Passport expiry date</fullName>
            </value>
            <value>
                <fullName>Annual Accounts</fullName>
            </value>
            <value>
                <fullName>AML Watchlists</fullName>
            </value>
            <value>
                <fullName>Power of Attorney expiry date</fullName>
            </value>
            <value>
                <fullName>Trust Agreement expiry date</fullName>
            </value>
            <value>
                <fullName>License expiry date</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Ongoing Monitoring</fullName>
            </value>
            <value>
                <fullName>Business Model</fullName>
            </value>
            <value>
                <fullName>Monthly Turnover volumes</fullName>
            </value>
            <value>
                <fullName>Websites</fullName>
            </value>
            <value>
                <fullName>Directors, Auth.Sign.</fullName>
            </value>
            <value>
                <fullName>UBO</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Bank Account</fullName>
            </value>
            <value>
                <fullName>Financial Accounts</fullName>
            </value>
            <value>
                <fullName>Website Checks</fullName>
            </value>
            <value>
                <fullName>Screening</fullName>
            </value>
            <value>
                <fullName>AML Risk Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/globalValueSets/Monitoring_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Postponed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <masterLabel>Monitoring Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MonitoringRecordPageController.cls
public class MonitoringRecordPageController {

    @AuraEnabled
    public static Monitoring__c getMonitoringById(String recordId){
        return [SELECT Id, Level__c, Reason__c, Monitoring_Status__c, User__c, Notes__c, Reason_Comment__c, Next_Monitoring_Date__c, Last_Monitoring_Date__c, Monitoring_Completed__c, Monitoring_Started_Date__c
                FROM Monitoring__c
                WHERE Id = :recordId
                LIMIT 1];  
    }

    @AuraEnabled
    public static List<ApplicationFormService.SectionWrapper> getMonitoringSections(String recordId) {
        List<ApplicationFormService.SectionWrapper> listOfMonitoringSection = new List<ApplicationFormService.SectionWrapper>();
        List<String> listOfSections = new List<String>();
        Map<String, Set<String>> mapOfMonitorinTypesBySection = getTypesOfMonitoringBySection();
        for (String section : mapOfMonitorinTypesBySection.keySet()) {
            listOfSections.add(section);
        }
        Map<String,List<ApplicationFormService.FieldWrapper>> mapOfFieldsBySection = getFieldsBySection(listOfSections, recordId);

        for (String section : mapOfMonitorinTypesBySection.keySet()) {
            ApplicationFormService.SectionWrapper monitoringSection = new ApplicationFormService.SectionWrapper();
            monitoringSection.label = section;
            monitoringSection.isMonitoringSection = section == 'Monitoring' ? true : false;
            monitoringSection.isPeriodKycSection = section == 'Periodic KYC Review' ? true : false;
            monitoringSection.fields = mapOfFieldsBySection.get(section);
            listOfMonitoringSection.add(monitoringSection);
        }
        return listOfMonitoringSection;
    }

    @AuraEnabled
    public static void updateMonitoringFields(String recordId, Map<String, Object> fieldsForUpdate) {
        Monitoring__c monitoring = [SELECT Id FROM Monitoring__c WHERE Id = :recordId LIMIT 1];

        for (String fieldName : fieldsForUpdate.keySet()) {
            String typeOfObject = CustomerDetailPageController.getFieldDataType('Monitoring__c', fieldName);

            if (typeOfObject != null) {
                Object fieldValue = fieldsForUpdate.get(fieldName);
                Object valueOfField = '';

                if (typeOfObject == ConstantUtility.CURRENCY_TYPE || typeOfObject == ConstantUtility.NUMBER_TYPE || typeOfObject == ConstantUtility.DOUBLE_TYPE) {
                    valueOfField = Decimal.valueOf((String) fieldValue);
                } else if (typeOfObject == ConstantUtility.DATE_TYPE) {
                    valueOfField = Date.valueOf((String) fieldValue);
                } else if (typeOfObject == ConstantUtility.DATE_TIME_TYPE) {
                    valueOfField = Datetime.valueOf((String) fieldValue);
                } else if (typeOfObject == ConstantUtility.MULTIPICKLIST) {
                    List<Object> fieldValues = (List<Object>) fieldValue;
                    for(Object value : fieldValues) {
                        valueOfField += value + ';' ;
                    }
                    String.valueOf(valueOfField).removeEnd(';');
                } else {
                    valueOfField = fieldValue;
                }

                if (valueOfField != null) {
                    monitoring.put(fieldName, valueOfField);
                }
            }
        }

        update monitoring;
    }

    @AuraEnabled
    public static void updateMonitoringTypeValues(List<Map<Object, Object>> listOfRecordsToUpdate) {
    List<Monitoring_Type__c> listOfMonitoringTypesToUpdate = new List<SObject>();

    for (Map<Object, Object> record : listOfRecordsToUpdate) {
        Id recordId = (Id)record.get('recordId');
        List<Object> fieldsToUpdate = (List<Object>)record.get('fieldsToUpdate');

        Monitoring_Type__c monitoringTypeToUpdate = new Monitoring_Type__c();
        monitoringTypeToUpdate.Id = recordId;

        for (Object fieldUpdate : fieldsToUpdate) {
            Map<Object, Object> mapOfValueByFieldApiToUpdate = (Map<Object, Object>)fieldUpdate;
            String apiNameOfField = (String)mapOfValueByFieldApiToUpdate.get('fieldApi');
            String typeOfObject = CustomerDetailPageController.getFieldDataType('Monitoring_Type__c', apiNameOfField);

            if (typeOfObject == ConstantUtility.CURRENCY_TYPE || typeOfObject == ConstantUtility.NUMBER_TYPE || typeOfObject == ConstantUtility.DOUBLE_TYPE) {
                monitoringTypeToUpdate.put(apiNameOfField, Decimal.valueOf((String)mapOfValueByFieldApiToUpdate.get('updatedValue')));
            } else if (typeOfObject == ConstantUtility.DATE_TYPE) {
                monitoringTypeToUpdate.put(apiNameOfField, Date.valueOf((String)mapOfValueByFieldApiToUpdate.get('updatedValue')));
            } else {
                monitoringTypeToUpdate.put(apiNameOfField, mapOfValueByFieldApiToUpdate.get('updatedValue'));
            }
        }

        listOfMonitoringTypesToUpdate.add(monitoringTypeToUpdate);
    }
    System.debug('listOfMonitoringTypesToUpdate ' + listOfMonitoringTypesToUpdate);
    update listOfMonitoringTypesToUpdate;
}


    @AuraEnabled
    public static Map<String,List<ApplicationFormService.FieldWrapper>>  getFieldsBySection(List<String> listOfSections, String recordId){

        Map<String,List<ApplicationFormService.FieldWrapper>> mapOfFieldsBySection = new Map<String,List<ApplicationFormService.FieldWrapper>>();
        List<ApplicationFormService.FieldWrapper> listOfMonitoringSectionFields = new List<ApplicationFormService.FieldWrapper>();
        List<ApplicationFormService.FieldWrapper> listOfKYCReviewSectionFields = new List<ApplicationFormService.FieldWrapper>();
        
        List<Monitoring_Type__c> listOfMonitoringTypes = [SELECT  Id, Monitoring__c, Section__c, Type__c, Status__c, Comment__c, Next_Date__c, Notify_Before_days__c 
                                                          FROM Monitoring_Type__c
                                                          WHERE Section__c IN :listOfSections
                                                          AND Monitoring__c = : recordId];
        System.debug('listOfMonitoringTypes ' + listOfMonitoringTypes);

        for(Monitoring_Type__c monitoringType : listOfMonitoringTypes) {
            ApplicationFormService.FieldWrapper field = new ApplicationFormService.FieldWrapper();
        
            if(monitoringType.Section__c == 'Monitoring') {
                field.typeOfMonitoring = monitoringType.Type__c;
                field.idOfMonitoring = monitoringType.Id;
                field.monitoringNextDate = monitoringType.Next_Date__c;
                field.monitoringNotifyBefore = monitoringType.Notify_Before_days__c;
                listOfMonitoringSectionFields.add(field);
            } else if(monitoringType.Section__c == 'Periodic KYC Review') {
                field.typeOfMonitoring = monitoringType.Type__c;
                field.idOfMonitoring = monitoringType.Id;
                field.options = getOptionsForMonitoringStatus(monitoringType.Type__c);
                field.statusOfMonitoring = monitoringType.Status__c;
                field.commentOfMonitoring = monitoringType.Comment__c;
                listOfKYCReviewSectionFields.add(field);
            }
        }
        mapOfFieldsBySection.put('Monitoring', listOfMonitoringSectionFields);
        mapOfFieldsBySection.put('Periodic KYC Review', listOfKYCReviewSectionFields);
        
        return mapOfFieldsBySection;
    }

    public static List<ApplicationFormService.OptionWrapper> getOptionsForMonitoringStatus(String nameOfMonitoringType) {

        List<ApplicationFormService.OptionWrapper> listOfFieldOptions = new List<ApplicationFormService.OptionWrapper>();

        List<String> listOfBusinessModelOptions = new List<String> {
            'Has not been changed',
            'Has changed'
        };

        List<String> listOfMonthlyTurnoverOptions = new List<String> { 
            'Lower than declared',
            'As expected',
            'Monthly turnover is higher than   declared'
        };
        
        List<String> listOfWebsiteOptions = new List<String> { 
            'Has not been changed',
            'Added new'
        };
        
        List<String> listOfStatusOptions = new List<String> { 
            'Pending',
            'Verified',
            'Postponed',
            'Rejected',
            'Not Started'
        };

        if(nameOfMonitoringType == 'Business Model') {
            for(String option : listOfBusinessModelOptions) {
                ApplicationFormService.OptionWrapper optionWrapper = new ApplicationFormService.OptionWrapper();
                optionWrapper.label = option;
                optionWrapper.value = option;
                listOfFieldOptions.add(optionWrapper);
            }
        } else if (nameOfMonitoringType == 'Monthly Turnover volumes') {
            for(String option : listOfMonthlyTurnoverOptions) {
                ApplicationFormService.OptionWrapper optionWrapper = new ApplicationFormService.OptionWrapper();
                optionWrapper.label = option;
                optionWrapper.value = option;
                listOfFieldOptions.add(optionWrapper);
            }
        } else if (nameOfMonitoringType == 'Websites') {
            for(String option : listOfWebsiteOptions) {
                ApplicationFormService.OptionWrapper optionWrapper = new ApplicationFormService.OptionWrapper();
                optionWrapper.label = option;
                optionWrapper.value = option;
                listOfFieldOptions.add(optionWrapper);
            }
        } else {
            for(String option : listOfStatusOptions) {
                ApplicationFormService.OptionWrapper optionWrapper = new ApplicationFormService.OptionWrapper();
                optionWrapper.label = option;
                optionWrapper.value = option;
                listOfFieldOptions.add(optionWrapper);
            }
        }
        return listOfFieldOptions;
    }

    public static Map<String, Set<String>> getTypesOfMonitoringBySection() {

        Map<String, Set<String>> mapOfMonitorinTypesBySection = new Map<String, Set<String>>();
        List<ApplicationFormService.OptionWrapper> listOfSectionValues = ApplicationFormService.getOptionsForPicklist('Section__c', 'Monitoring_Type__c');
        for(ApplicationFormService.OptionWrapper section : listOfSectionValues) {
            if(section.label == 'Monitoring') {
                mapOfMonitorinTypesBySection.put(section.label, ConstantUtility.SET_OF_MONITORING_SECTION_TYPES);
            } else if(section.label == 'Periodic KYC Review') {
                mapOfMonitorinTypesBySection.put(section.label, ConstantUtility.SET_OF_KYC_REVIEW_SECTION_TYPES);
            }
        }

    return mapOfMonitorinTypesBySection;
    }
}