force-app/main/default/objects/Monitoring__c/Monitoring__c.object-meta.xml
<CustomObject>
    <label>Monitoring</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Monitoring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitorings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring_Type__c/Monitoring_Type__c.object-meta.xml
<CustomObject>
    <label>Monitoring Type</label>
    <nameField>
        <label>Monitoring Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring_Type__c/fields/Monitoring__c.field-meta.xml
<CustomField>
    <fullName>Monitoring__c</fullName>
    <label>Monitoring</label>
    <referenceTo>Monitoring__c</referenceTo>
    <relationshipLabel>Monitoring Types</relationshipLabel>
    <relationshipName>Monitoring_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Periodic KYC Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Has not been changed</fullName>
            </value>
            <value>
                <fullName>Has changed</fullName>
            </value>
            <value>
                <fullName>Lower than declared</fullName>
            </value>
            <value>
                <fullName>As expected</fullName>
            </value>
            <value>
                <fullName>Monthly turnover is higher than declared:</fullName>
            </value>
            <value>
                <fullName>Added new</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good Standing Dates</fullName>
            </value>
            <value>
                <fullName>Corporate Doc. Update</fullName>
            </value>
            <value>
                <fullName>Government Doc. Update</fullName>
            </value>
            <value>
                <fullName>UBO Passport expiry date</fullName>
            </value>
            <value>
                <fullName>Annual Accounts</fullName>
            </value>
            <value>
                <fullName>AML Watchlists</fullName>
            </value>
            <value>
                <fullName>Power of Attorney expiry date</fullName>
            </value>
            <value>
                <fullName>Trust Agreement expiry date</fullName>
            </value>
            <value>
                <fullName>License expiry date</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Ongoing Monitoring</fullName>
            </value>
            <value>
                <fullName>Business Model</fullName>
            </value>
            <value>
                <fullName>Monthly Turnover volumes</fullName>
            </value>
            <value>
                <fullName>Websites</fullName>
            </value>
            <value>
                <fullName>Directors, Auth.Sign.</fullName>
            </value>
            <value>
                <fullName>UBO</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Bank Account</fullName>
            </value>
            <value>
                <fullName>Financial Accounts</fullName>
            </value>
            <value>
                <fullName>Website Checks</fullName>
            </value>
            <value>
                <fullName>Screening</fullName>
            </value>
            <value>
                <fullName>AML Risk Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MonitoringTriggerHandler.cls
public class MonitoringTriggerHandler {

    public void onAfterInsert(List<Monitoring__c> listOfMonitoring) {
        createMonitoringTypesForMonitoring(listOfMonitoring);
    }

    public static void createMonitoringTypesForMonitoring(List<Monitoring__c> listOfMonitoring) {

        Map<String, Set<String>> mapOfMonitorinTypesBySection = getTypesOfMonitoringBySection();
        List<Monitoring_Type__c> listOfMonitoringTypesForInsert = new List<Monitoring_Type__c>();

        for(Monitoring__c monitoring : listOfMonitoring){
            for (String section : mapOfMonitorinTypesBySection.keySet()) {
                Set<String> monitoringTypes = mapOfMonitorinTypesBySection.get(section);
        
                for (String type : monitoringTypes) {
                    Monitoring_Type__c monitoringType = new Monitoring_Type__c();
                    monitoringType.Section__c = section;
                    monitoringType.Type__c = type;
                    monitoringType.Monitoring__c = monitoring.Id;
                    if(type != 'Business Model' && type != 'Monthly Turnover volumes' && type != 'Websites' && section == 'Periodic KYC Review') {
                        monitoringType.Status__c = 'Not Started';
                    }

                    listOfMonitoringTypesForInsert.add(monitoringType);
                }
            }
        }
        insert listOfMonitoringTypesForInsert;
    }    
    
    public static Map<String, Set<String>> getTypesOfMonitoringBySection() {

        Map<String, Set<String>> mapOfMonitorinTypesBySection = new Map<String, Set<String>>();
        List<ApplicationFormService.OptionWrapper> listOfSectionValues = ApplicationFormService.getOptionsForPicklist('Section__c', 'Monitoring_Type__c');
        System.debug('logLevel' + listOfSectionValues);
        for(ApplicationFormService.OptionWrapper section : listOfSectionValues) {
            if(section.label == 'Monitoring') {
                mapOfMonitorinTypesBySection.put(section.label, ConstantUtility.SET_OF_MONITORING_SECTION_TYPES);
            } else if(section.label == 'Periodic KYC Review') {
                mapOfMonitorinTypesBySection.put(section.label, ConstantUtility.SET_OF_KYC_REVIEW_SECTION_TYPES);
            }
        }

    return mapOfMonitorinTypesBySection;
    }
}