force-app/main/default/objects/Monitoring__c/Monitoring__c.object-meta.xml
<CustomObject>
    <label>Monitoring</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Monitoring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitorings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring__c/fields/Monitoring_Status__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Status__c</fullName>
    <label>Monitoring Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Monitoring_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/Monitoring_Type__c.object-meta.xml
<CustomObject>
    <label>Monitoring Type</label>
    <nameField>
        <label>Monitoring Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring_Type__c/fields/Monitoring__c.field-meta.xml
<CustomField>
    <fullName>Monitoring__c</fullName>
    <label>Monitoring</label>
    <referenceTo>Monitoring__c</referenceTo>
    <relationshipLabel>Monitoring Types</relationshipLabel>
    <relationshipName>Monitoring_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Periodic KYC Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Has not been changed</fullName>
            </value>
            <value>
                <fullName>Has changed</fullName>
            </value>
            <value>
                <fullName>Lower than declared</fullName>
            </value>
            <value>
                <fullName>As expected</fullName>
            </value>
            <value>
                <fullName>Monthly turnover is higher than declared:</fullName>
            </value>
            <value>
                <fullName>Added new</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monitoring_Type__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good Standing Dates</fullName>
            </value>
            <value>
                <fullName>Corporate Doc. Update</fullName>
            </value>
            <value>
                <fullName>Government Doc. Update</fullName>
            </value>
            <value>
                <fullName>UBO Passport expiry date</fullName>
            </value>
            <value>
                <fullName>Annual Accounts</fullName>
            </value>
            <value>
                <fullName>AML Watchlists</fullName>
            </value>
            <value>
                <fullName>Power of Attorney expiry date</fullName>
            </value>
            <value>
                <fullName>Trust Agreement expiry date</fullName>
            </value>
            <value>
                <fullName>License expiry date</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Ongoing Monitoring</fullName>
            </value>
            <value>
                <fullName>Business Model</fullName>
            </value>
            <value>
                <fullName>Monthly Turnover volumes</fullName>
            </value>
            <value>
                <fullName>Websites</fullName>
            </value>
            <value>
                <fullName>Directors, Auth.Sign.</fullName>
            </value>
            <value>
                <fullName>UBO</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Bank Account</fullName>
            </value>
            <value>
                <fullName>Financial Accounts</fullName>
            </value>
            <value>
                <fullName>Website Checks</fullName>
            </value>
            <value>
                <fullName>Screening</fullName>
            </value>
            <value>
                <fullName>AML Risk Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/globalValueSets/Monitoring_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Postponed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <masterLabel>Monitoring Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MonitoringTypeTriggerHandler.cls
public class MonitoringTypeTriggerHandler {

    public void onAfterUpdate(List<Monitoring_Type__c> listOfMonitoringType) {
        updateMonitoringStatus(listOfMonitoringType);
    }
    
    public static void updateMonitoringStatus(List<Monitoring_Type__c> listOfMonitoringType) {

        String finalStatusOfMonitoring;
        Set<Id> setOfIdMonitoring = new Set<Id>();
        List<Monitoring__c> listOfMonitoringsForUpdate = new List<Monitoring__c>();
        Map<Id, Set<String>> mapOfStatusesByMonitoring = new Map<Id, Set<String>>();
        Map<Id, String> mapOfFinalStatusById = new Map<Id, String>();

        for(Monitoring_Type__c monitoring : listOfMonitoringType) {
            setOfIdMonitoring.add(monitoring.Monitoring__c);
        }

        List<Monitoring_Type__c> listOfMonitoringTypes = [SELECT Id, Status__c, Section__c, Type__c, Monitoring__c
                                                    FROM Monitoring_Type__c 
                                                    WHERE Monitoring__c IN : setOfIdMonitoring 
                                                    AND Section__c = 'Periodic KYC Review' 
                                                    AND Type__c != 'Business Model'
                                                    AND Type__c != 'Monthly Turnover volumes'
                                                    AND Type__c != 'Websites'];

        for (Monitoring_Type__c monitoring : listOfMonitoringTypes) {

            Id idOfMonitoringType = monitoring.Monitoring__c;
    
            String statusOfMonitoringType = monitoring.Status__c;
    
            if (mapOfStatusesByMonitoring.containsKey(idOfMonitoringType)) {
                mapOfStatusesByMonitoring.get(idOfMonitoringType).add(statusOfMonitoringType);
            } else {
                Set<String> setOfMonitoringTypeStatuses = new Set<String>{statusOfMonitoringType};
                mapOfStatusesByMonitoring.put(idOfMonitoringType, setOfMonitoringTypeStatuses);
            }
        }

        for (Id monitoringId : mapOfStatusesByMonitoring.keySet()) {

            Set<String> setOfStatuses = mapOfStatusesByMonitoring.get(monitoringId);
            System.debug('setOfStatuses' + setOfStatuses);
            if(setOfStatuses.contains('Rejected')) {
                mapOfFinalStatusById.put(monitoringId, 'Rejected');
            } else if(setOfStatuses.contains('Postponed')) {
                mapOfFinalStatusById.put(monitoringId, 'Postponed');
            } else if(setOfStatuses.size() == 1 && setOfStatuses.contains('Verified')) {
                mapOfFinalStatusById.put(monitoringId, 'Verified');
            } else {
                mapOfFinalStatusById.put(monitoringId, 'Pending');
            }
        }

        for(Id monitoringId : mapOfFinalStatusById.keySet()) {
            listOfMonitoringsForUpdate.add(new Monitoring__c(Id = monitoringId, Monitoring_Status__c = mapOfFinalStatusById.get(monitoringId)));
        }
        System.debug('listOfMonitoringsForUpdate ' +  listOfMonitoringsForUpdate);
        update listOfMonitoringsForUpdate;
    }

}