force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Certified_Documents__c.field-meta.xml
<CustomField>
    <fullName>Certified_Documents__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certified Documents</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Certified_Organizational_Chart__c.field-meta.xml
<CustomField>
    <fullName>Certified_Organizational_Chart__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certified Organizational Chart</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Compliance_policies__c.field-meta.xml
<CustomField>
    <fullName>Compliance_policies__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Compliance policies</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Country_of_citizenship_of_UBO__c.field-meta.xml
<CustomField>
    <fullName>Country_of_citizenship_of_UBO__c</fullName>
    <label>Country of citizenship of UBO ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries_for_AML</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Country_of_incorporation_of_the_Corpora__c.field-meta.xml
<CustomField>
    <fullName>Country_of_incorporation_of_the_Corpora__c</fullName>
    <label>Country of incorporation of the Corpora</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries_for_AML</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Country_of_residence_of_UBO__c.field-meta.xml
<CustomField>
    <fullName>Country_of_residence_of_UBO__c</fullName>
    <label>Country of residence of UBO ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries_for_AML</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Date_of_AML__c.field-meta.xml
<CustomField>
    <fullName>Date_of_AML__c</fullName>
    <label>Date of AML</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Enhanced_Periodic_KYC__c.field-meta.xml
<CustomField>
    <fullName>Enhanced_Periodic_KYC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enhanced Periodic KYC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Enhanced_TM__c.field-meta.xml
<CustomField>
    <fullName>Enhanced_TM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enhanced TM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Enhanced_Webshield__c.field-meta.xml
<CustomField>
    <fullName>Enhanced_Webshield__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enhanced Webshield</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Enhnaced_Sanction_Screening__c.field-meta.xml
<CustomField>
    <fullName>Enhnaced_Sanction_Screening__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enhnaced Sanction Screening</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <defaultValue>false</defaultValue>
    <label>License</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/MLRO_Approval__c.field-meta.xml
<CustomField>
    <fullName>MLRO_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MLRO Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Nationality_of_UBO__c.field-meta.xml
<CustomField>
    <fullName>Nationality_of_UBO__c</fullName>
    <label>Nationality of UBO ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries_for_AML</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/fields/SOW_SOF__c.field-meta.xml
<CustomField>
    <fullName>SOW_SOF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SOW/SOF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <label>License</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Month_Transaction__c/Month_Transaction__c.object-meta.xml
<CustomObject>
    <label>Month Transaction</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Month Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Month_Transaction__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Month Transactions</relationshipLabel>
    <relationshipName>Month_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Month_Transaction__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/core/objects/Opportunity/recordTypes/Upsale.recordType-meta.xml
<RecordType>
    <fullName>Upsale</fullName>
    <active>true</active>
    <businessProcess>Upsale</businessProcess>
    <label>Upsale</label>
</RecordType>

force-app/main/default/globalValueSets/Countries_for_AML.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BLANK</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Svalbard and Mayen</fullName>
    </customValue>
    <customValue>
        <fullName>Tokelau</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>Faroe islands</fullName>
    </customValue>
    <customValue>
        <fullName>Iceland</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>San Marino</fullName>
    </customValue>
    <customValue>
        <fullName>Greenland</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Vatican City State (Holy See)</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuania</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Christmas Island</fullName>
    </customValue>
    <customValue>
        <fullName>Cocos (Keeling) Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Norfolk Island</fullName>
    </customValue>
    <customValue>
        <fullName>French Polynesia</fullName>
    </customValue>
    <customValue>
        <fullName>Guadeloupe</fullName>
    </customValue>
    <customValue>
        <fullName>Mayotte</fullName>
    </customValue>
    <customValue>
        <fullName>New Caledonia</fullName>
    </customValue>
    <customValue>
        <fullName>Saint Barthélemy</fullName>
    </customValue>
    <customValue>
        <fullName>Saint Martin (French part)</fullName>
    </customValue>
    <customValue>
        <fullName>Saint Pierre and Miquelon</fullName>
    </customValue>
    <customValue>
        <fullName>Wallis and Futuna</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>French Guiana</fullName>
    </customValue>
    <masterLabel>Countries for AML</masterLabel>
</GlobalValueSet>

force-app/main/core/classes/utils/ConstantUtility.cls
public class ConstantUtility {

    public static final String ERROR_MESSAGE = 'The request failed. Status code:';
    public static final String ACCOUNT = 'Account';
    public static final String LEAD = 'Lead';
    public static final String CONTACT = 'Contact';
    public static final String OPPORTUNITY = 'Opportunity';
    public static final String RESELLER = 'Reseller';
    public static final String CUSTOMER = 'Customer__c';

    public static final String HEAD_OF_MERCHANT = 'Head of Merchant Onboarding Team';
    public static final String CHIEF_COMPLIANCE = 'Chief Compliance Officer/MLRO';
    public static final String SYSTEM_ADMINISTRATOR = 'System Administrator';
    public static final String AML_OFFICER = 'AML Officer';

    public static final String HIGH_RISK = 'High Risk';
    public static final String MEDIUM_RISK = 'Medium Risk';
    public static final String LOW_RISK = 'Low Risk';
    public static final String LWC_ERROR = 'LWC Error';

    public static final String PICKLIST = 'PICKLIST';
    public static final String LISTBOX = 'LISTBOX';
    public static final String BLANK = 'BLANK';
    public static final String TEXT = 'TEXT';
    public static final String CHECKBOX = 'CHECKBOX';
    public static final String REFERENCE = 'REFERENCE';
    public static final String TEXTAREA = 'TEXTAREA';
    public static final String CURRENCY_TYPE = 'CURRENCY';
    public static final String NUMBER_TYPE = 'NUMBER';
    public static final String DATE_TYPE = 'DATE';
    public static final String DATE_TIME_TYPE = 'DATETIME';
    public static final String DOUBLE_TYPE = 'DOUBLE';
    public static final String MULTIPICKLIST = 'MULTIPICKLIST';


    public static final String COUNTRY = 'Country';
    public static final String GEOGRAPHICAL_RISK = 'Geographical Risk';
    public static final String COUNTRY_OF_INCORPORATION = 'Country_of_incorporation_of_the_Corpora__c';
    public static final String COUNTRY_OF_CITIZENSHIP = 'Country_of_citizenship_of_UBO__c';
    public static final String NATIONALITY_OF_UBO = 'Nationality_of_UBO__c';
    public static final String COUNTRY_OF_RESIDENCE = 'Country_of_residence_of_UBO__c';
    public static final String OTHER_INDUSTRY = 'Other_Business_Industry_Activity__c';
    public static final String MONTH_FIELD = 'Month__c';
    public static final String MONTH_TRANSACTION ='Month_Transaction__c';
    public static final String DATE_OF_AML = 'Date_of_AML__c';

    public static final String SENT_STATUS = 'Sent';
    public static final String ONBOARDING_STATUS = 'Onboarding';
    public static final String SENT_TO_APPROVE_STATUS = 'Sent to Approve';
    public static final String ACTIVE_STATUS = 'Active';
    public static final String REJECTED_STATUS = 'Rejected';
    public static final String ANSWERED_STATUS = 'Answered';
    public static final String POSTPONED_STATUS = 'Postponed';
    public static final String APPROVED_STATUS = 'Approved';
    public static final String PENDING_STATUS = 'Pending';
    public static final String REQUESTED_STATUS = 'Requested';
    public static final String NOT_APPLICABLE_STATUS = 'Not Applicable';
    public static final String BANK_ACCOUNTS = 'Bank Accounts';
    public final static String VERIFIED_STATUS = 'Verified';
    public final static String COMPLETED_STATUS = 'Completed';

    public static final String AML_RISK_LEVEL = 'AML Risk Level';
    public static final String AML_RISK_ASSESSMENT = 'Customer Risk Assessment';
    public static final String LAST_MONTHS_TRANSACTIONS = 'Last Months Transactions';
    public static final String DETAILS_PAGE = 'Details Page';
    public static final String OTHER = 'Other';
    public static final String ENHANCED_CDD = 'Enhanced CDD';
    public static final String MONTH = 'Month';
    public static final String AMOUNT = 'Amount';

    public static final String CORPORATE_TYPE = 'Corporate';
    public static final String SOW_SOF_TYPE = 'SOW/SOF';
    public static final String INDIVIDUAL_TYPE = 'Individual';

    public static final String TEMPLATE_FOR_LEADS_WITHOUT_SCORE = 'Noda_Email_When_Score_0';

    public static final String DOCTYPE_UNKNOWN = 'doctype:unknown';

    public static final String CARDS_PROCESSING = 'Cards Processing';
    public static final String OPEN_BANKING_PAY_INS = 'Open Banking Pay-ins';

    public static final String NOT_STARTED_MONITORING_STATUS = 'Not Started';
    public static final String MONITORING_LABEL = 'Monitoring';

    public static final String PERIODIC_KYC_REVIEW = 'Periodic KYC Review';
    public static final String BUSINESS_MODEL = 'Business Model';
    public static final String MONTHLY_TURNOVER_VOLUMES = 'Monthly Turnover volumes';
    public static final String WEBSITES = 'Websites';
    public static final String STATUSES = 'Statuses';

    public static final String SALESFORCE_LICENSE = 'Salesforce';

    public static final String UPSALE = 'Upsale';
    public static final String NEGOTIATION = 'Negotiation';
    public static final String MEETING = 'Meeting';

    public static final String DIGITAL_LEAD_GROUP = 'Digital_Lead_Managers';
    public static final String SUPERVISOR = 'Supervisor';
    public static final String NODA_ADDRESS = 'sales@noda.live';

    public static final Integer TEXT_FIELD_LENGTH = 255;

    public static final Integer MAXIMUM_NUMBER_OF_COUNTRIES = 3;

    public static final List<String> MONITORING_TYPES_NOT_FOR_NOT_STARTED_STATUS = new List<String>{
        BUSINESS_MODEL, MONTHLY_TURNOVER_VOLUMES, WEBSITES
    };

    public static final List<String> AML_RISK_SECTION_FIELDS = new List<String>{
        'Enhanced_Periodic_KYC__c',
        'SOW_SOF__c',
        'Compliance_policies__c',
        'Enhanced_Webshield__c',
        'License__c',
        'Enhnaced_Sanction_Screening__c',
        'Certified_Documents__c',
        'Enhanced_TM__c',
        'Certified_Organizational_Chart__c',
        'MLRO_Approval__c'
    };

    public static final Set<String> SET_OF_MONITORING_SECTION_TYPES = new Set<String>{
        'Good Standing Dates', 'Corporate Doc. Update', 'Government Doc. Update', 'UBO Passport expiry date',
        'Annual Accounts', 'AML Watchlists', 'Power of Attorney expiry date', 'Trust Agreement expiry date',
        'License expiry date', 'Follow-up', 'Ongoing Monitoring'
    };

    public static final Set<String> SET_OF_KYC_REVIEW_SECTION_TYPES = new Set<String>{
        'Business Model','Monthly Turnover volumes', 'Websites', 'Corporate Doc. Update', 'Government Doc. Update', 'Directors, Auth.Sign.',
        'UBO', 'License', 'Bank Account', 'Financial Accounts', 'Website Checks', 'Screening', 'AML Risk Level'
    };

    public static final Set<String> SET_OF_UBO_DOCUMENTS = new Set<String>{
        'SOF','SOW', 'CV of UBO'
    };

    public static final Set<String> SET_OF_INDIVIDUAL_DOCUMENTS = new Set<String>{
        'Proof of Identity', 'Proof of Residence', 'Document of Trust'
    };

    public static final Set<String> SET_OF_CORPORATE_DIRECTOR_DOCUMENTS = new Set<String>{
        'Certificate of Incorporation','Register of Directors', 'Document of Trust'
    };

    public static final Set<String> SET_OF_INDIVIDUAL_GOVERNMENT_DOCUMENTS = new Set<String>{
        'Excerpt from the Business Register'
    };

    public static final Set<String> SET_OF_CORPORATE_GOVERNMENT_DIRECTOR_DOCUMENTS = new Set<String>{
        'Excerpt from the Business Register','Registered Directors'
    };

    public static final Set<String> SET_OF_CORPORATE_KYC_DOCUMENTS = new Set<String>{
        'Certificate of Incorporation', 'M&A', 'Register of Shareholders', 'Document of Trust'
    };
    public static final Set<String> SET_OF_GOVERNMENT_KYC_DOCUMENTS = new Set<String>{
        'Excerpt from the Business Register', 'Registered Directors', 'Registered Shareholders'
    };

    public static final Set<String> SET_OF_EXISTING_ICONS = new Set<String>{
        'ai','attachment','audio','box_notes','csv','eps','excel','exe',
        'flash','folder','gdoc','gdocs','gform','gpres','gsheet','html',
        'keynote','library_folder','image','link','mp4','overlay','pack',
        'pages','pdf','ppt','psd','quip_doc','quip_sheet','xml','visio',
        'rtf','slide','stypi','txt','video','zip','webex','word','quip_slide'
    };

    public static final String POLICIES_PROCEDURES_SECTION_LICENSE_TYPE = 'Policies & Procedures';
    public static final String EXAMPLES_KYC_PACKS_SECTION_LICENSE_TYPE = 'Examples of KYC packs';

    public static final Set<String> SET_OF_SECTION_WITH_LICENSE_TYPES = new Set<String> {
        EXAMPLES_KYC_PACKS_SECTION_LICENSE_TYPE,
        POLICIES_PROCEDURES_SECTION_LICENSE_TYPE
    };

    public static final Set<String> SET_OF_SECTION_WITH_MONITORING_TYPES = new Set<String> {
        'Monitoring',
        'Periodic KYC Review'
    };

    public static final Set<String> SET_OF_LICENSE_DOCUMENTS = new Set<String> {
        'Provided Licence',
        'Excerpt from the Regulator Register',
        'Service Agreement between Payment Agent and License Holder'
    };

    public static final String WWW_PREFIX_URL = 'www.';
    public static final String SLASH = '/';

    // GoogleWebHook class constants
    public static final String API_KEY = 'api-key';
    public static final String SUCCESS = 'success';
    public static final String DIGITAL_MARKETING = 'Digital Marketing';
    public static final String SCORE = 'score';
    public static final String LEAD_ID = 'leadId';
    public static final String EMAIL = 'email';
    public static final String WEBSITE = 'website';

    // NodaHubRestService class constants
    public static final String OBJECT_NAME = 'objectName';
    public static final String FIELD_NAME = 'fieldName';
    public static final String PRODUCTS = 'Products';
}