force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/AML_Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>AML_Risk_Level__c</fullName>
    <label>AML Risk Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low Risk</fullName>
            </value>
            <value>
                <fullName>Medium Risk</fullName>
            </value>
            <value>
                <fullName>High Risk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/fields/AML_Risk_Matrix_ver__c.field-meta.xml
<CustomField>
    <fullName>AML_Risk_Matrix_ver__c</fullName>
    <label>AML Risk Matrix ver.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Approved_by__c.field-meta.xml
<CustomField>
    <fullName>Approved_by__c</fullName>
    <label>Approved/Rejected by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <formula>Approver_Name__r.FirstName + &apos; &apos; +  Approver_Name__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approver</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Approver_Position__c.field-meta.xml
<CustomField>
    <fullName>Approver_Position__c</fullName>
    <formula>Approver_Name__r.Profile.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approver Position</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Name_Surname__c.field-meta.xml
<CustomField>
    <fullName>Name_Surname__c</fullName>
    <label>Name Surname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Review_Completed__c.field-meta.xml
<CustomField>
    <fullName>Review_Completed__c</fullName>
    <label>Review Completed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Review_Started__c.field-meta.xml
<CustomField>
    <fullName>Review_Started__c</fullName>
    <label>Review Started</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Uploading Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Onboarding</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Termination in Process</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Disconnection in Process</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Sent to Approve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Setting__c/Form_Setting__c.object-meta.xml
<CustomObject>
    <label>Form Setting</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Form Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Setting__c/fields/AML_Tool_Version__c.field-meta.xml
<CustomField>
    <fullName>AML_Tool_Version__c</fullName>
    <label>AML Tool Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Setting__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <label>Form Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AML Risk Level</fullName>
            </value>
            <value>
                <fullName>Details Page</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>UBO</fullName>
            </value>
            <value>
                <fullName>Directors/Auth.Sign. KYC</fullName>
            </value>
            <value>
                <fullName>Corporate KYC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerTriggerHandler.cls
public class CustomerTriggerHandler {

    public void onBeforeUpdate(Map<Id,Customer__c> oldMap, Map<Id,Customer__c> newMap) {

        Set<Id> setOfApprovedOrRejectedId = new Set<Id>();

        for(Customer__c customer : newMap.values()) {

            if(customer.Status__c != oldMap.get(customer.Id).Status__c) {
                if(customer.Status__c == ConstantUtility.ONBOARDING_STATUS) {
                    customer.Review_Started__c = System.today();
                }
                if(customer.Status__c == ConstantUtility.SENT_TO_APPROVE_STATUS) {
                    customer.Review_Completed__c = System.today();
                }
                if(customer.Status__c == ConstantUtility.ACTIVE_STATUS || customer.Status__c == ConstantUtility.REJECTED_STATUS) {
                    customer.Approved_by__c = customer.Approver_Position__c;
                    customer.Name_Surname__c = customer.Approver__c;
                }
            }
            if(customer.AML_Risk_Level__c != oldMap.get(customer.Id).AML_Risk_Level__c || customer.Score__c != oldMap.get(customer.Id).Score__c) {
                customer.AML_Risk_Matrix_ver__c = getAMLRiskVersion();
            }
        }
    }

    public static String getAMLRiskVersion() {

        return [SELECT Id, AML_Tool_Version__c FROM Form_Setting__c WHERE Form_Type__c = :ConstantUtility.AML_RISK_LEVEL AND Active__c = TRUE].AML_Tool_Version__c;
    }
}