force-app/main/default/objects/Approver_Comment__c/Approver_Comment__c.object-meta.xml
<CustomObject>
    <label>Approver Comment</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Approver Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approver Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approver_Comment__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approver_Comment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Approver Comments</relationshipLabel>
    <relationshipName>Approver_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approver_Comment__c/fields/Onboarding_Officer__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_Comments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approver_Comment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/AML_Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>AML_Risk_Level__c</fullName>
    <label>AML Risk Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low Risk</fullName>
            </value>
            <value>
                <fullName>Medium Risk</fullName>
            </value>
            <value>
                <fullName>High Risk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <formula>Approver_Name__r.FirstName + &apos; &apos; +  Approver_Name__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approver</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <defaultValue>false</defaultValue>
    <label>License</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Onboarding_Officer__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customers3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Registered_Address__c.field-meta.xml
<CustomField>
    <fullName>Registered_Address__c</fullName>
    <label>Registered Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Uploading Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Onboarding</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Termination in Process</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Disconnection in Process</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Sent to Approve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <label>License</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Website__c/Website__c.object-meta.xml
<CustomObject>
    <label>Website</label>
    <nameField>
        <label>Service name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Websites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Website__c/fields/Age_Restriction__c.field-meta.xml
<CustomField>
    <fullName>Age_Restriction__c</fullName>
    <label>Age Restriction (if applicable)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Wibsites_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/AML_policy__c.field-meta.xml
<CustomField>
    <fullName>AML_policy__c</fullName>
    <label>AML policy (if applicable)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Wibsites_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Comply_Advantage_Screening__c.field-meta.xml
<CustomField>
    <fullName>Comply_Advantage_Screening__c</fullName>
    <label>Comply Advantage Screening</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Website__c/fields/Contact_Us_email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_email__c</fullName>
    <label>Contact Us (email)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Website__c/fields/Contact_Us_phone__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_phone__c</fullName>
    <label>Contact Us (phone)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Website__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Websites</relationshipLabel>
    <relationshipName>Websites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Website__c/fields/Domain_Ownership_in_WhoIs__c.field-meta.xml
<CustomField>
    <fullName>Domain_Ownership_in_WhoIs__c</fullName>
    <label>Domain Ownership in WhoIs</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anonymous</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Different entity</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Free_Trial_period__c.field-meta.xml
<CustomField>
    <fullName>Free_Trial_period__c</fullName>
    <label>Free Trial period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Risk</fullName>
            </value>
            <value>
                <fullName>Tangible Goods</fullName>
            </value>
            <value>
                <fullName>Intangible Goods</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Other Restricted Industries</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <label>Legal Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Wibsites_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <label>License (if applicable)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Wibsites_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Privacy_Policy__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy__c</fullName>
    <label>Privacy Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Wibsites_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Refund_Policy__c.field-meta.xml
<CustomField>
    <fullName>Refund_Policy__c</fullName>
    <label>Refund Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Wibsites_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Registered_Address__c.field-meta.xml
<CustomField>
    <fullName>Registered_Address__c</fullName>
    <label>Registered Address</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Wibsites_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Subscriptions_Membership__c.field-meta.xml
<CustomField>
    <fullName>Subscriptions_Membership__c</fullName>
    <label>Subscriptions/Membership</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/T_C__c.field-meta.xml
<CustomField>
    <fullName>T_C__c</fullName>
    <label>T&amp;C</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Wibsites_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Website__c/fields/Test_Account_Password__c.field-meta.xml
<CustomField>
    <fullName>Test_Account_Password__c</fullName>
    <label>Test Account Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Website__c/fields/Test_Account_Username__c.field-meta.xml
<CustomField>
    <fullName>Test_Account_Username__c</fullName>
    <label>Test Account Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Website__c/fields/Website_Included_in_the_License__c.field-meta.xml
<CustomField>
    <fullName>Website_Included_in_the_License__c</fullName>
    <label>Website Included in the License</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Website__c/fields/Website_Overall__c.field-meta.xml
<CustomField>
    <fullName>Website_Overall__c</fullName>
    <label>Website Overall</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weak</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>CZK</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>EGP</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>HRK</fullName>
    </customValue>
    <customValue>
        <fullName>HUF</fullName>
    </customValue>
    <customValue>
        <fullName>KWD</fullName>
    </customValue>
    <customValue>
        <fullName>NOK</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>OMR</fullName>
    </customValue>
    <customValue>
        <fullName>PLN</fullName>
    </customValue>
    <customValue>
        <fullName>QAR</fullName>
    </customValue>
    <customValue>
        <fullName>RON</fullName>
    </customValue>
    <customValue>
        <fullName>RSD</fullName>
    </customValue>
    <customValue>
        <fullName>SAR</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR</fullName>
    </customValue>
    <customValue>
        <fullName>THB</fullName>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>TWD</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Wibsites_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Requested to add</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Wibsites Picklist</masterLabel>
</GlobalValueSet>

force-app/main/core/globalValueSets/Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DynamicModalWindowController.cls
public class DynamicModalWindowController {

    @AuraEnabled
    public static List<User> getApprovers(String recordId){

        List<User> listOfUser = new List<User>();
        Customer__c customer = [SELECT Id, AML_Risk_Level__c FROM Customer__c WHERE Id = :recordId LIMIT 1];
        String amlRiskLevel = customer.AML_Risk_Level__c;

        if(amlRiskLevel != null) {
            if(amlRiskLevel == ConstantUtility.HIGH_RISK) {
                listOfUser = [SELECT Id, Name, Profile.Name FROM User WHERE Profile.Name  = :ConstantUtility.CHIEF_COMPLIANCE];
            } else {
                listOfUser = [SELECT Id, Name, Profile.Name FROM User WHERE Profile.Name  = :ConstantUtility.CHIEF_COMPLIANCE OR Profile.Name = :ConstantUtility.HEAD_OF_MERCHANT];
            }
        }
        return listOfUser;
    }

    @AuraEnabled
    public static List<User> getComplianceTeamMembers(String recordId){

        return [SELECT Id, Name, Profile.Name FROM User WHERE Profile.Name  = :ConstantUtility.CHIEF_COMPLIANCE OR Profile.Name = :ConstantUtility.HEAD_OF_MERCHANT OR Profile.Name = :ConstantUtility.AML_OFFICER];

    }

    @AuraEnabled
    public static List<Website__c> getWebsites(String recordId){

        String idOfCustomer = [SELECT Id, Customer__c FROM Website__c WHERE Id = :recordId LIMIT 1].Customer__c;
        return [SELECT Id, Name FROM Website__c WHERE Customer__c = :idOfCustomer AND Id != :recordId];

    }

    @AuraEnabled
    public static Approver_Comment__c createCommentFromApprover(String recordId, String userId, String message){
        
        String idOfOnboardingOfficer;
        List<Customer__c> listOfCustomer = [SELECT Id, Status__c, Onboarding_Officer__c FROM Customer__c WHERE Id = :recordId];
        List<Customer__c> listOfCustomerForUpdate = new List<Customer__c>();

        for(Customer__c customer : listOfCustomer) {
            idOfOnboardingOfficer = customer.Onboarding_Officer__c;
            customer.Status__c = ConstantUtility.ONBOARDING_STATUS;
            listOfCustomerForUpdate.add(customer);
        }

        Approver_Comment__c approverCommentForInsert = new Approver_Comment__c(
                Customer__c = recordId,
                Approver__c = userId,
                Message__c = message,
                Onboarding_Officer__c = idOfOnboardingOfficer,
                Status__c = ConstantUtility.SENT_STATUS
        );
        insert approverCommentForInsert;
        update listOfCustomerForUpdate;
        return approverCommentForInsert;
    }

    @AuraEnabled
    public static List<Approver_Comment__c> updateApproverCommentWithAnswer(String recordId, String answer){
        
        String idOfOnboardingOfficer;
        List<Customer__c> listOfCustomer = [SELECT Id, Status__c FROM Customer__c WHERE Id = :recordId];
        List<Approver_Comment__c> listOfApproverComment = [ SELECT Id,Answer__c, Customer__c, Status__c FROM Approver_Comment__c WHERE Customer__c = :recordId];
        List<Customer__c> listOfCustomerForUpdate = new List<Customer__c>();
        List<Approver_Comment__c> listOfApproverCommentForUpdate = new List<Approver_Comment__c>();


        for(Customer__c customer : listOfCustomer) {
            customer.Status__c = ConstantUtility.SENT_TO_APPROVE_STATUS;
            listOfCustomerForUpdate.add(customer);
        }

        for(Approver_Comment__c approverComment : listOfApproverComment) {
            approverComment.Answer__c = answer;
            approverComment.Status__c = ConstantUtility.ANSWERED_STATUS;
            listOfApproverCommentForUpdate.add(approverComment);
        }
        update listOfApproverCommentForUpdate;
        update listOfCustomerForUpdate;
        return listOfApproverCommentForUpdate;
    }

    @AuraEnabled
    public static Website__c copyWebsiteData(String recordId, String idOfWebsite){

        Website__c initialWebsite = [SELECT Age_Restriction__c, AML_policy__c, Category__c, Comply_Advantage_Screening__c, Contact_Us_email__c, Contact_Us_phone__c, Currency__c, Date__c,
                                        Domain_Ownership_in_WhoIs__c, Free_Trial_period__c, Industry__c, Legal_Name__c, License__c, Privacy_Policy__c, Refund_Policy__c, Registered_Address__c,
                                        Status__c, Subscriptions_Membership__c, T_C__c,  Test_Account_Password__c, Test_Account_Username__c, Website_Included_in_the_License__c, Website_Overall__c
                                FROM Website__c
                                WHERE Id = :idOfWebsite
                                LIMIT 1];

        Website__c websiteForUpdate = new Website__c();
        websiteForUpdate.Id = recordId;
        websiteForUpdate.Age_Restriction__c = initialWebsite.Age_Restriction__c;
        websiteForUpdate.AML_policy__c = initialWebsite.AML_policy__c;
        websiteForUpdate.Category__c = initialWebsite.Category__c;
        websiteForUpdate.Comply_Advantage_Screening__c = initialWebsite.Comply_Advantage_Screening__c;
        websiteForUpdate.Contact_Us_email__c = initialWebsite.Contact_Us_email__c;
        websiteForUpdate.Contact_Us_phone__c = initialWebsite.Contact_Us_phone__c;
        websiteForUpdate.Currency__c = initialWebsite.Currency__c;
        websiteForUpdate.Date__c = initialWebsite.Date__c;
        websiteForUpdate.Domain_Ownership_in_WhoIs__c = initialWebsite.Domain_Ownership_in_WhoIs__c;
        websiteForUpdate.Free_Trial_period__c = initialWebsite.Free_Trial_period__c;
        websiteForUpdate.Industry__c = initialWebsite.Industry__c;
        websiteForUpdate.Legal_Name__c = initialWebsite.Legal_Name__c;
        websiteForUpdate.License__c = initialWebsite.License__c;
        websiteForUpdate.Privacy_Policy__c = initialWebsite.Privacy_Policy__c;
        websiteForUpdate.Refund_Policy__c = initialWebsite.Refund_Policy__c;
        websiteForUpdate.Registered_Address__c = initialWebsite.Registered_Address__c;
        websiteForUpdate.Status__c = initialWebsite.Status__c;
        websiteForUpdate.Subscriptions_Membership__c = initialWebsite.Subscriptions_Membership__c;
        websiteForUpdate.T_C__c = initialWebsite.T_C__c;
        websiteForUpdate.Test_Account_Password__c = initialWebsite.Test_Account_Password__c;
        websiteForUpdate.Test_Account_Username__c = initialWebsite.Test_Account_Username__c;
        websiteForUpdate.Website_Included_in_the_License__c = initialWebsite.Website_Included_in_the_License__c;
        websiteForUpdate.Website_Overall__c = initialWebsite.Website_Overall__c;

        update websiteForUpdate;
        return websiteForUpdate;

    }
}