force-app/main/default/objects/Approver_Comment__c/Approver_Comment__c.object-meta.xml
<CustomObject>
    <label>Approver Comment</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Approver Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approver Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approver_Comment__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approver_Comment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Approver Comments</relationshipLabel>
    <relationshipName>Approver_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approver_Comment__c/fields/Onboarding_Officer__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_Comments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approver_Comment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <formula>Approver_Name__r.FirstName + &apos; &apos; +  Approver_Name__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approver</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Is_Complete__c.field-meta.xml
<CustomField>
    <fullName>Is_Complete__c</fullName>
    <formula>AND(
     NOT(ISBLANK(TEXT(AML_Risk_Level__c))),
    TRUE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Onboarding_Officer__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customers3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Uploading Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Onboarding</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Termination in Process</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Disconnection in Process</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Sent to Approve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Unanswered_Comments__c.field-meta.xml
<CustomField>
    <fullName>Unanswered_Comments__c</fullName>
    <label>Unanswered Comments</label>
    <summaryFilterItems>
        <field>Approver_Comment__c.Status__c</field>
        <operation>equals</operation>
        <value>Sent</value>
    </summaryFilterItems>
    <summaryForeignKey>Approver_Comment__c.Customer__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/ApprovalPanelController.cls
public without sharing class ApprovalPanelController {

    @AuraEnabled
    public static Customer__c getInfoFromCustomer(String recordId){

        return [SELECT Id, Name, Status__c, Is_Complete__c, Approver_Name__c, Unanswered_Comments__c,Onboarding_Officer__c FROM Customer__c WHERE Id = :recordId LIMIT 1];
        
    }

    @AuraEnabled
    public static Boolean checkIfUserIsSystemAdministrator(){
        
        String nameOfUserProfile = [SELECT Name FROM Profile WHERE Id =: UserInfo.getProfileId()].Name;
        
        if(nameOfUserProfile == ConstantUtility.SYSTEM_ADMINISTRATOR){
            return true;
        }else{
            return false;
        } 
    }

    @AuraEnabled
    public static Boolean checkIfUserHadPermissionForNewCustomer(){
        
        String nameOfUserProfile = [SELECT Name FROM Profile WHERE Id =: UserInfo.getProfileId()].Name;
        if(nameOfUserProfile == ConstantUtility.CHIEF_COMPLIANCE || nameOfUserProfile == ConstantUtility.HEAD_OF_MERCHANT || nameOfUserProfile == ConstantUtility.SYSTEM_ADMINISTRATOR){
            return true;
        }else{
            return false;
        } 
    }

    @AuraEnabled
    public static ApproverCommentWrapper getApproverComment(String recordId) {
        ApproverCommentWrapper wrapper = new ApproverCommentWrapper();
        
        List<Approver_Comment__c> listOfApproverComments = [
            SELECT Customer__c, Message__c, Status__c, Approver__r.Name
            FROM Approver_Comment__c
            WHERE Customer__c = :recordId AND Status__c = :ConstantUtility.SENT_STATUS
        ];
        
        wrapper.nameOfApprover = listOfApproverComments.isEmpty() ? null : listOfApproverComments[0].Approver__r.Name;
        wrapper.comments = listOfApproverComments.isEmpty() ? null : listOfApproverComments[0].Message__c;
        
        return wrapper;
    }

    public class ApproverCommentWrapper {
        @AuraEnabled
        public String nameOfApprover { get; set; }
        
        @AuraEnabled
        public String comments { get; set; }
    }
}