force-app/main/default/objects/Director__c/Director__c.object-meta.xml
<CustomObject>
    <label>Directors/Auth.Sign. KYC</label>
    <nameField>
        <label>Legal/Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Directors/Auth.Sign. KYC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Director__c.field-meta.xml
<CustomField>
    <fullName>Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Directors/Auth.Sign. KYC</label>
    <referenceTo>Director__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Visibility_Type__c.field-meta.xml
<CustomField>
    <fullName>Visibility_Type__c</fullName>
    <label>Visibility Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>SOW/SOF</fullName>
            </value>
            <value>
                <fullName>UBO</fullName>
                <isActive>false</isActive>
                <label>UBO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Document.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Copy</fullName>
    </customValue>
    <customValue>
        <fullName>Excerpt</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Apostilled</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Document</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DirectorTriggerHandler.cls
public class DirectorTriggerHandler {

    public void onAfterInsert(List<Director__c> listOfDirectors) {
        createRelatedDocuments(listOfDirectors);
    }

    public void createRelatedDocuments(List<Director__c> listOfDirectors) {

        List<Document__c> listOfDocumentsForInsert = new List<Document__c>();

        for(Director__c director : listOfDirectors) {
            for(String document : ConstantUtility.SET_OF_INDIVIDUAL_DOCUMENTS) {
                Document__c recordOfDocument = new Document__c();
                recordOfDocument.Name = document;
                recordOfDocument.Director__c = director.Id;
                recordOfDocument.Visibility_Type__c = 'Individual';
                listOfDocumentsForInsert.add(recordOfDocument);
            }
            for(String document : ConstantUtility.SET_OF_CORPORATE_DIRECTOR_DOCUMENTS) {
                Document__c recordOfDocument = new Document__c();
                recordOfDocument.Name = document;
                recordOfDocument.Director__c = director.Id;
                recordOfDocument.Visibility_Type__c = 'Corporate';
                listOfDocumentsForInsert.add(recordOfDocument);
            }
        }

        insert listOfDocumentsForInsert;
    }
}