force-app/main/default/objects/Corporate_KYC__c/Corporate_KYC__c.object-meta.xml
<CustomObject>
    <label>Corporate KYC</label>
    <nameField>
        <label>Legal/Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate KYC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Corporate_KYC__c.field-meta.xml
<CustomField>
    <fullName>Corporate_KYC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate KYC</label>
    <referenceTo>Corporate_KYC__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Document.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Copy</fullName>
    </customValue>
    <customValue>
        <fullName>Excerpt</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Apostilled</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Document</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CorporateKycTriggerHandler.cls
public class CorporateKycTriggerHandler {
    public void onAfterInsert(List<Corporate_KYC__c> listOfCorporateKYC) {
        createRelatedDocuments(listOfCorporateKYC);
    }

    public void createRelatedDocuments(List<Corporate_KYC__c> listOfCorporateKYC) {

        List<Document__c> listOfDocumentsForInsert = new List<Document__c>();

        for(Corporate_KYC__c corporateKYC : listOfCorporateKYC) {
            for(String document : ConstantUtility.SET_OF_CORPORATE_KYC_DOCUMENTS) {
                Document__c recordOfDocument = new Document__c();
                recordOfDocument.Name = document;
                recordOfDocument.Corporate_KYC__c = corporateKYC.Id;
                listOfDocumentsForInsert.add(recordOfDocument);
            }
        }

        insert listOfDocumentsForInsert;
    }
}