force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/UBO__c.field-meta.xml
<CustomField>
    <fullName>UBO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UBO</label>
    <referenceTo>UBO__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Visibility_Type__c.field-meta.xml
<CustomField>
    <fullName>Visibility_Type__c</fullName>
    <label>Visibility Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>SOW/SOF</fullName>
            </value>
            <value>
                <fullName>UBO</fullName>
                <isActive>false</isActive>
                <label>UBO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UBO__c/UBO__c.object-meta.xml
<CustomObject>
    <label>UBO</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UBO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Document.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Copy</fullName>
    </customValue>
    <customValue>
        <fullName>Excerpt</fullName>
    </customValue>
    <customValue>
        <fullName>Certified</fullName>
    </customValue>
    <customValue>
        <fullName>Apostilled</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Document</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UBOTriggerHandler.cls
public class UBOTriggerHandler {
    
    public void onAfterInsert(List<UBO__c> listOfUbo) {
        createRelatedDocuments(listOfUbo);
    }

    public void createRelatedDocuments(List<UBO__c> listOfUbo) {

        List<Document__c> listOfDocumentsForInsert = new List<Document__c>();

        for(UBO__c ubo : listOfUbo) {
            for(String document : ConstantUtility.SET_OF_INDIVIDUAL_DOCUMENTS) {
                Document__c recordOfDocument = new Document__c();
                recordOfDocument.Name = document;
                recordOfDocument.UBO__c = ubo.Id;
                recordOfDocument.Visibility_Type__c = 'Individual';
                listOfDocumentsForInsert.add(recordOfDocument);
            }
            for(String document : ConstantUtility.SET_OF_UBO_DOCUMENTS) {
                Document__c recordOfDocument = new Document__c();
                recordOfDocument.Name = document;
                recordOfDocument.UBO__c = ubo.Id;
                recordOfDocument.Visibility_Type__c = 'SOW/SOF';
                listOfDocumentsForInsert.add(recordOfDocument);
            }
        }

        insert listOfDocumentsForInsert;
    }
}