force-app/main/default/objects/Lead/fields/General_Traffic__c.field-meta.xml
<CustomField>
    <fullName>General_Traffic__c</fullName>
    <label>General Traffic</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/core/objects/Lead/fields/GEOText__c.field-meta.xml
<CustomField>
    <fullName>GEOText__c</fullName>
    <label>Supported GEO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Other_GEO__c.field-meta.xml
<CustomField>
    <fullName>Other_GEO__c</fullName>
    <label>Other GEO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/core/objects/Lead/fields/Traffic__c.field-meta.xml
<CustomField>
    <fullName>Traffic__c</fullName>
    <label>Supported GEO Traffic</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/core/classes/utils/LeadUtils.cls
public with sharing class LeadUtils {
    public Utils utilsCls {
        get {
            if (utilsCls == null) {
                utilsCls = new Utils();
            }

            return utilsCls;
        }
        set;
    }

    public Lead updateIndustryOfLead(Lead lead) {
        String industry = SimilarWebRestApiService.getIndustryOfWebsite(utilsCls.getCorrectLinkOfWebsite(lead.Website));

        lead.Industry__c = industry;

        return lead;
    }

    public Lead updateTrafficOfLead(Lead lead, Map<Boolean, Map<String, String>> countryCodesStringsByBooleans) {
        Map<String, String> supportedCountryCodeByName = countryCodesStringsByBooleans.get(true);
        Map<String, String> unsupportedCountryCodeByName = countryCodesStringsByBooleans.get(false);

        String correctedUrl = utilsCls.getCorrectLinkOfWebsite(lead.Website);

        Map<String, String> mapOfTrafficByCountryCode = SimilarWebRestApiService.getCountryAndTrafficFromWebsite(correctedUrl, supportedCountryCodeByName, unsupportedCountryCodeByName);

        lead.GEOText__c = mapOfTrafficByCountryCode.get('valueOfSupportedGeoField');
        lead.Traffic__c = mapOfTrafficByCountryCode.get('valueOfSupportedTraffic') != null ? Decimal.valueOf(mapOfTrafficByCountryCode.get('valueOfSupportedTraffic')) : 0;
        lead.Other_GEO__c = mapOfTrafficByCountryCode.get('valueOfUnsupportedGeoField');
        lead.General_Traffic__c = mapOfTrafficByCountryCode.get('valueOfGeneralTraffic') != null ? Decimal.valueOf(mapOfTrafficByCountryCode.get('valueOfGeneralTraffic')) : 0;

        return lead;
    }
}