force-app/main/core/objects/Lead/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <label>Activity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/core/objects/Lead/fields/OwnerFullName__c.field-meta.xml
<CustomField>
    <fullName>OwnerFullName__c</fullName>
    <formula>IF( left(OwnerId, 3) = &quot;005&quot; ,
Owner:User.FirstName  + &quot; &quot; + Owner:User.LastName ,
			Owner:Queue.QueueName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner full name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Score_Formula__c.field-meta.xml
<CustomField>
    <fullName>Score_Formula__c</fullName>
    <formula>IF(
    ISBLANK(Website) || CONTAINS( $Setup.Noda_Custom_Settings__c.Domainst_Black_List__c , Website), 0,
    IF(
        General_Traffic__c &lt; 5000, 0,
        IF(
            AND(5000 &lt; General_Traffic__c, General_Traffic__c &lt;= 20000), 1,
            IF(
                AND(20000 &lt; General_Traffic__c, General_Traffic__c &lt;= 50000), 2,
                IF(
                    AND(50000 &lt; General_Traffic__c, General_Traffic__c &lt;= 100000), 3,
                    IF(
                        AND(100000 &lt; General_Traffic__c, General_Traffic__c &lt;= 300000), 4,
                        IF(
                            General_Traffic__c &gt; 300000, 5,
                            null
                        )
                    )
                )
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/core/classes/selectors/LeadSelector.cls
public inherited sharing class LeadSelector {
    public static Decimal getLeadScore(Id leadId) {
        return [
            SELECT
                Score_Formula__c
            FROM Lead
            WHERE Id = :leadId
        ].Score_Formula__c;
    }

    public static List<Lead> getLeadByEmailAndWebsite(String email) {
        return [
            SELECT Score_Formula__c
            FROM Lead
            WHERE Email = :email AND Website != null
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
    }

    public static List<Lead> getLeadActivityDate(Set<Id> setOfLeadIds) {
        return [
            SELECT Id, Activity_Date__c 
            FROM Lead 
            WHERE Id IN :setOfLeadIds
        ];
    }

    public static List<Lead> getLeadRows(String searchKey) {
        return [
            SELECT Id, Name, Industry, Company, OwnerFullName__c, Website, Status, LeadSource, Activity_Date__c
            FROM Lead
            WHERE Name LIKE :searchKey
            OR Website LIKE :searchKey
            OR Company LIKE :searchKey
        ];
    }
}