force-app/main/core/objects/Lead/fields/Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Owner_Email__c</fullName>
    <formula>IF( left(OwnerId, 3) = &quot;005&quot; ,
Owner:User.Email ,
Owner:Queue.QueueName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Email</label>
    <type>Text</type>
</CustomField>

force-app/main/core/objects/Lead/fields/OwnerFullName__c.field-meta.xml
<CustomField>
    <fullName>OwnerFullName__c</fullName>
    <formula>IF( left(OwnerId, 3) = &quot;005&quot; ,
Owner:User.FirstName  + &quot; &quot; + Owner:User.LastName ,
			Owner:Queue.QueueName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner full name</label>
    <type>Text</type>
</CustomField>

force-app/main/core/objects/Noda_Custom_Settings__c/Noda_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Noda Custom Settings</label>
</CustomObject>

force-app/main/core/objects/Noda_Custom_Settings__c/fields/Org_URL__c.field-meta.xml
<CustomField>
    <fullName>Org_URL__c</fullName>
    <label>Org URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/core/classes/services/EmailService.cls
public with sharing class EmailService {  

    public static void sendEmails(List<SObject> listOfRecords, String[] toAddresses, Id addressId, String subject) {
        List<Messaging.SingleEmailMessage> listOfSingleEmailMessages = buildEmailTemplate(listOfRecords, toAddresses, addressId, subject);

        List<Messaging.SendEmailResult> listOfSendEmailResults = Messaging.sendEmail(listOfSingleEmailMessages, false);
            for (Messaging.SendEmailResult sendEmailResultItem : listOfSendEmailResults) {

                if (!sendEmailResultItem.isSuccess()) {
                    LoggerUtil.error('Email did not send ' + sendEmailResultItem.getErrors().toString());
                }
            }
    }
    public static List<Messaging.SingleEmailMessage> buildEmailTemplate(List<SObject> listOfRecords, String[] toAddresses, Id addressId, String subject) {
        List<Messaging.SingleEmailMessage> listOfSingleEmailMessages = new List<Messaging.SingleEmailMessage>();
        String body;
        if(!listOfRecords.isEmpty()) {
            for(SObject record : listOfRecords) {
                SObjectType sobjectType = record.Id.getSObjectType();
                if (sobjectType == Lead.sObjectType) {  
                    toAddresses.add((String)record.get('Owner_Email__c'));
                    body = buildNewDigitalLeadBody(record);
                }
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(toAddresses);
                    mail.setSubject(subject);
                    mail.setOrgWideEmailAddressId(addressId);
                    mail.setHtmlBody(body);
                    listOfSingleEmailMessages.add(mail);
            }
        }            
            
        return listOfSingleEmailMessages;  
    }

    private static String buildNewDigitalLeadBody(SObject record) {
        Noda_Custom_Settings__c nodaCustomSettings = Noda_Custom_Settings__c.getOrgDefaults();

        String link = nodaCustomSettings.Org_URL__c + record.Id;

        String body = String.format(Label.newDigitalLeadEmail, new List<Object>{
            (String)record.get('LastName'), (String)record.get('FirstName'), (String)record.get('OwnerFullName__c'), link
        });
            
        return body;  
    }

}  